/*!
  @file           gos220.h
  @author         RaymondR
  @brief          Microsoft Cluster Server   ( generated by AppWizard! )
  @see            

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end



\endif
*/



#ifndef GOS220_H
#define GOS220_H


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

//#define VC_EXTRALEAN		         // Exclude rarely-used stuff from Windows headers
#define _ATL_APARTMENT_THREADED
#define WINVER 0x0500

#ifndef _UNICODE
# define _UNICODE		
#endif

#include <afxwin.h>			// MFC core and standard components
#include <afxext.h>			// MFC extensions
#include <afxdisp.h>
#include <afxtempl.h>

#ifndef _AFX_NO_AFXCMN_SUPPORT
# include <afxcmn.h>			
#endif 

#include <atlbase.h>

extern CComModule _Module;

#include <atlcom.h>
#include <clusapi.h>

/*===========================================================================*
 *  DEFINES                                                                  *
 *===========================================================================*/


/*===========================================================================*
 *  MACROS                                                                   *
 *===========================================================================*/


/*===========================================================================*
 *  CLASSES, STRUCTURES, TYPES, UNIONS ...                                   *
 *===========================================================================*/

typedef UINT	IDS;
typedef UINT	IDD;


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/


/*===========================================================================*
 *  PRAGMA                                                                   *
 *===========================================================================*/


#pragma warning(disable : 4100)		// unreferenced formal parameters
#pragma warning(disable : 4702)		// unreachable code
#pragma warning(disable : 4711)		// function selected for automatic inline expansion

// Link against the Microsoft Windows NT Cluster API library.
#pragma comment(lib, "clusapi.lib")

// Link against the Cluster Administrator Extensions library.
#pragma comment(lib, "cluadmex.lib")

// Link against Resource Utilities library.
#pragma comment(lib, "resutils.lib")


#endif  /* GOS220_H */
