# -----------------------------------------------------------------------------
# module:    default.mac
#
# responsible: DL_SAP_DB_INTERFACES
#
# special area: Makes the all of the Interface Runtime Library
# description:
#
# see:
#
# change history:
# -----------------------------------------------------------------------------
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

#::sdk/libReuseSDK.lib
::SAPDB/Interfaces/sapdbifr.lib
::SAPDB/Interfaces/tools/sqldbc_cons.lnk distrib
::SAPDB/Interfaces/tools/sqlcli.lnk distrib
::SAPDB/Interfaces/errmsg.mac
