/*
        ========== licence begin  GPL
        Copyright (c) 2006 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end

*/

#ifndef SDBMSG_SHAREDSQL_H
#define SDBMSG_SHAREDSQL_H
/*
This header file was generated by buildmsg.pl
--- Do not edit....
*/
#ifdef __cplusplus
#ifndef MSG_LIST_HPP
#include "SAPDB/Messages/Msg_List.hpp"
#endif
#ifndef MSG_ARG_HPP
#include "SAPDB/Messages/Msg_Arg.hpp"
#endif
#ifndef MSG_SIMPLEARG_HPP
#include "SAPDB/Messages/Msg_SimpleArg.hpp"
#endif
#endif

#ifndef SDB_RELEASE_070600  /* don't merge this define - only this date: 2006-01-25 11:42:40 */
#error SDBMsg_SharedSQL.h was probably integrated between releases, do not integrate this header file, \
use buildmsg
#endif


#define SDBMSG_SHAREDSQL_COMPONENT "SharedSQL"
/* Begin of all message defines for component SharedSQL -> */
/* Begin of defines for message CREATE_INSTANCE: ID = 1, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_CREATE_INSTANCE 1, "SharedSQL", __FILE__, __LINE__, "Creating instance SharedSQL failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message CREATE_INSTANCE */
/* Begin of defines for message NO_MEMORY: ID = 2, VERSION = 1, TAGS = 2 -> */
#define SDBMSG_SHAREDSQL_NO_MEMORY 2, "SharedSQL", __FILE__, __LINE__, "Out of Memory", (Msg_Has2Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_NO_MEMORY__MEMREQUEST "MEMREQUEST"
/* <- End of defines for message NO_MEMORY */
/* Begin of defines for message CREATE_TEMP_FILE: ID = 3, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_CREATE_TEMP_FILE 3, "SharedSQL", __FILE__, __LINE__, "Creating temporary file failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message CREATE_TEMP_FILE */
/* Begin of defines for message WRITE_TEMP_FILE: ID = 4, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_WRITE_TEMP_FILE 4, "SharedSQL", __FILE__, __LINE__, "Writing to temporary file failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message WRITE_TEMP_FILE */
/* Begin of defines for message READ_TEMP_FILE: ID = 5, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_READ_TEMP_FILE 5, "SharedSQL", __FILE__, __LINE__, "Temporary file could not be read", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message READ_TEMP_FILE */
/* Begin of defines for message DELETE_TEMP_FILE: ID = 6, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_DELETE_TEMP_FILE 6, "SharedSQL", __FILE__, __LINE__, "Deleting from temporary file failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message DELETE_TEMP_FILE */
/* Begin of defines for message UNLOAD_DATA: ID = 7, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_UNLOAD_DATA 7, "SharedSQL", __FILE__, __LINE__, "Flushing failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_UNLOAD_DATA__SHAREDSQLCOMMANDID "SHAREDSQLCOMMANDID" /* optional */
/* <- End of defines for message UNLOAD_DATA */
/* Begin of defines for message RELOAD_DATA: ID = 8, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_RELOAD_DATA 8, "SharedSQL", __FILE__, __LINE__, "Reload failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_RELOAD_DATA__SHAREDSQLCOMMANDID "SHAREDSQLCOMMANDID" /* optional */
/* <- End of defines for message RELOAD_DATA */
/* Begin of defines for message DELETE_DATA: ID = 9, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_DELETE_DATA 9, "SharedSQL", __FILE__, __LINE__, "Delete failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_DELETE_DATA__SHAREDSQLCOMMANDID "SHAREDSQLCOMMANDID" /* optional */
/* <- End of defines for message DELETE_DATA */
/* Begin of defines for message HASHTABLE: ID = 10, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_HASHTABLE 10, "SharedSQL", __FILE__, __LINE__, "Hash table internal error", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message HASHTABLE */
/* Begin of defines for message LRULIST: ID = 11, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_LRULIST 11, "SharedSQL", __FILE__, __LINE__, "LRU list internal error", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message LRULIST */
/* Begin of defines for message ILLEGAL_OPERATION: ID = 12, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_ILLEGAL_OPERATION 12, "SharedSQL", __FILE__, __LINE__, "Illegal operation", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ILLEGAL_OPERATION */
/* Begin of defines for message PUTPARSEID: ID = 13, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTPARSEID 13, "SharedSQL", __FILE__, __LINE__, "Parse ID could not be added", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_PUTPARSEID__PARSEID "PARSEID" /* optional */
/* <- End of defines for message PUTPARSEID */
/* Begin of defines for message PUTPLAN: ID = 14, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTPLAN 14, "SharedSQL", __FILE__, __LINE__, "Execution plan could not be added", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message PUTPLAN */
/* Begin of defines for message PUTPLAN_DUPKEY: ID = 15, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTPLAN_DUPKEY 15, "SharedSQL", __FILE__, __LINE__, "Insert with duplicate key", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message PUTPLAN_DUPKEY */
/* Begin of defines for message PUTPLAN_NOMEM: ID = 16, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTPLAN_NOMEM 16, "SharedSQL", __FILE__, __LINE__, "No memory for new tree node", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message PUTPLAN_NOMEM */
/* Begin of defines for message PUTPLAN_INVALIDID: ID = 17, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTPLAN_INVALIDID 17, "SharedSQL", __FILE__, __LINE__, "Invalid parse ID", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_SHAREDSQL_PUTPLAN_INVALIDID__PARSEID "PARSEID" /* optional */
#define SDBMSGTAG_SHAREDSQL_PUTPLAN_INVALIDID__SHAREDSQLPARSEID "SHAREDSQLPARSEID" /* optional */
/* <- End of defines for message PUTPLAN_INVALIDID */
/* Begin of defines for message CREATE_COMMAND: ID = 18, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_CREATE_COMMAND 18, "SharedSQL", __FILE__, __LINE__, "Creating command failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message CREATE_COMMAND */
/* Begin of defines for message COMPARE_COMMANDS: ID = 19, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_COMPARE_COMMANDS 19, "SharedSQL", __FILE__, __LINE__, "Commands could not be compaired", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message COMPARE_COMMANDS */
/* Begin of defines for message COPYHANDLE: ID = 20, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_COPYHANDLE 20, "SharedSQL", __FILE__, __LINE__, "Handle could not be copied", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message COPYHANDLE */
/* Begin of defines for message CREATE_LOCKS: ID = 21, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_CREATE_LOCKS 21, "SharedSQL", __FILE__, __LINE__, "Creating locks failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message CREATE_LOCKS */
/* Begin of defines for message PUTTABLES: ID = 22, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_SHAREDSQL_PUTTABLES 22, "SharedSQL", __FILE__, __LINE__, "Adding table information failed", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message PUTTABLES */
/* <- End of message defines for component SharedSQL */

/* some helpful enumerations (created by buildmsg.pl) -> */

#define SDBMSG_SHAREDSQL_ENUMERATION \
                    SharedSQL_CREATE_INSTANCE=1, \
                    SharedSQL_NO_MEMORY=2, \
                    SharedSQL_CREATE_TEMP_FILE=3, \
                    SharedSQL_WRITE_TEMP_FILE=4, \
                    SharedSQL_READ_TEMP_FILE=5, \
                    SharedSQL_DELETE_TEMP_FILE=6, \
                    SharedSQL_UNLOAD_DATA=7, \
                    SharedSQL_RELOAD_DATA=8, \
                    SharedSQL_DELETE_DATA=9, \
                    SharedSQL_HASHTABLE=10, \
                    SharedSQL_LRULIST=11, \
                    SharedSQL_ILLEGAL_OPERATION=12, \
                    SharedSQL_PUTPARSEID=13, \
                    SharedSQL_PUTPLAN=14, \
                    SharedSQL_PUTPLAN_DUPKEY=15, \
                    SharedSQL_PUTPLAN_NOMEM=16, \
                    SharedSQL_PUTPLAN_INVALIDID=17, \
                    SharedSQL_CREATE_COMMAND=18, \
                    SharedSQL_COMPARE_COMMANDS=19, \
                    SharedSQL_COPYHANDLE=20, \
                    SharedSQL_CREATE_LOCKS=21, \
                    SharedSQL_PUTTABLES=22
#define SDBMSG_SHAREDSQL_INITIALIZATIONLIST(x) \
                    x(SDBMSG_SHAREDSQL_CREATE_INSTANCE, "CREATE_INSTANCE"), \
                    x(SDBMSG_SHAREDSQL_NO_MEMORY, "NO_MEMORY"), \
                    x(SDBMSG_SHAREDSQL_CREATE_TEMP_FILE, "CREATE_TEMP_FILE"), \
                    x(SDBMSG_SHAREDSQL_WRITE_TEMP_FILE, "WRITE_TEMP_FILE"), \
                    x(SDBMSG_SHAREDSQL_READ_TEMP_FILE, "READ_TEMP_FILE"), \
                    x(SDBMSG_SHAREDSQL_DELETE_TEMP_FILE, "DELETE_TEMP_FILE"), \
                    x(SDBMSG_SHAREDSQL_UNLOAD_DATA, "UNLOAD_DATA"), \
                    x(SDBMSG_SHAREDSQL_RELOAD_DATA, "RELOAD_DATA"), \
                    x(SDBMSG_SHAREDSQL_DELETE_DATA, "DELETE_DATA"), \
                    x(SDBMSG_SHAREDSQL_HASHTABLE, "HASHTABLE"), \
                    x(SDBMSG_SHAREDSQL_LRULIST, "LRULIST"), \
                    x(SDBMSG_SHAREDSQL_ILLEGAL_OPERATION, "ILLEGAL_OPERATION"), \
                    x(SDBMSG_SHAREDSQL_PUTPARSEID, "PUTPARSEID"), \
                    x(SDBMSG_SHAREDSQL_PUTPLAN, "PUTPLAN"), \
                    x(SDBMSG_SHAREDSQL_PUTPLAN_DUPKEY, "PUTPLAN_DUPKEY"), \
                    x(SDBMSG_SHAREDSQL_PUTPLAN_NOMEM, "PUTPLAN_NOMEM"), \
                    x(SDBMSG_SHAREDSQL_PUTPLAN_INVALIDID, "PUTPLAN_INVALIDID"), \
                    x(SDBMSG_SHAREDSQL_CREATE_COMMAND, "CREATE_COMMAND"), \
                    x(SDBMSG_SHAREDSQL_COMPARE_COMMANDS, "COMPARE_COMMANDS"), \
                    x(SDBMSG_SHAREDSQL_COPYHANDLE, "COPYHANDLE"), \
                    x(SDBMSG_SHAREDSQL_CREATE_LOCKS, "CREATE_LOCKS"), \
                    x(SDBMSG_SHAREDSQL_PUTTABLES, "PUTTABLES")
/* <- some helpful enumerations */

#endif /* SDBMSG_SHAREDSQL_H */
