# -----------------------------------------------------------------------------
# module:    default.mac
#
# responsible: DL_SAP_DB_INTERFACES
#
# special area: Makes all of the Interface Runtime Testsuite
# description:
#
# see:
#
# change history:
# -----------------------------------------------------------------------------
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

::SAPDB/Interfaces/tests/StmtExecute.lnk
::SAPDB/Interfaces/tests/StmtExecuteU.lnk
::SAPDB/Interfaces/tests/FailedStmt.lnk
::SAPDB/Interfaces/tests/FailedPreparedStmt.lnk
::SAPDB/Interfaces/tests/InsStmtExe.lnk
::SAPDB/Interfaces/tests/QueryStmt.lnk
::SAPDB/Interfaces/tests/Resultset.lnk
::SAPDB/Interfaces/tests/lobtypestest.lnk
::SAPDB/Interfaces/tests/SimpleNavigation.lnk
::SAPDB/Interfaces/tests/MassNavigation.lnk
::SAPDB/Interfaces/tests/FetchTypes.lnk
::SAPDB/Interfaces/tests/FailedFetchTypes.lnk
::SAPDB/Interfaces/tests/FetchPrevious.lnk
::SAPDB/Interfaces/tests/mttest.lnk
::SAPDB/Interfaces/tests/illegalparam.lnk
::SAPDB/Interfaces/tests/applparamtest.lnk
::SAPDB/Interfaces/tests/invdata.lnk
::SAPDB/Interfaces/tests/Blobtst001.lnk
::SAPDB/Interfaces/tests/getobject.lnk
::SAPDB/Interfaces/tests/dataexecute.lnk
::SAPDB/Interfaces/tests/NullVal.lnk
::SAPDB/Interfaces/tests/pspytest.lnk
::SAPDB/Interfaces/tests/getrow.lnk
::SAPDB/Interfaces/tests/RowSetPos.lnk
::SAPDB/Interfaces/tests/applshared.lnk
::SAPDB/Interfaces/tests/updinsert.lnk
::SAPDB/Interfaces/tests/upddelete.lnk
::SAPDB/Interfaces/tests/updupdate.lnk
#::SAPDB/Interfaces/tests/testclink.mac
