/*!******************************************************************************

  @file         hgg01.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HGG01_H
#define HGG01_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x07\xac\xfe\x5e\x00\x7a\x72\x18\x0b\x41\x32\xb0\xe8\xc1\xfe\x59'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "ggg04.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal pasbool g01aggr_optim ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01align (
    tsp00_Int4               val);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01backup_block_count ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01auto_recreate_bad_indexes ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01cache_size (
    tgg04_CacheType_Param     cache_type);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01catalog_cache_init_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01check_mxgg (
    pasbool               &  ok);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01columncompression ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01checktablewidth ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01datapart_init (
    tgg00_MessBlock       &  mblock,
    tgg00_DataPartPtr        datapart_ptr,
    tsp00_Int4               datapart_size);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01deadlock_detection ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01default_configuration ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01diag_minmax_optim ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01diag_reverse_fetch ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01optimize_parallel_server ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01dump (
    tgg00_VfFileref       &  hostfile,
    tsp00_Page            &  buf,
    tsp00_Int4            &  out_pno,
    integer               &  out_pos,
    tsp00_VfReturn        &  host_err,
    tsp00_ErrText         &  errtext);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01dw_io_area_flush ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01dw_io_area_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01dw_lru_tail_flush ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01GetSessionAuxCounter (
    tgg00_TransContext    &  t);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01hashed_resultset ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01inittabid ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01int4incr (
    tsp00_C4              &  intvalue);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01is_livecache ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01is_archive ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01join_hash_min_ratio ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int2 g01join_maxtab_level4 ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int2 g01join_maxtab_level9 ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01join_parall_minsize ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01join_prefetch_percent ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01join_tablebuffer ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tgg00_JoinSearchLevel_Param g01join_search_level ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01kb_work_st_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01kb_workbuf_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01key_assign (
    tgg00_Lkey            &  source_key,
    tgg00_Lkey            &  target_key,
    tgg00_BasisError      &  e);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01key_and_len_assign (
    tsp00_Key             &  source_key,
    tsp00_Int4               source_key_len,
    tsp00_Key             &  target_key,
    tsp00_Int2            &  target_key_len,
    tgg00_BasisError      &  e);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01lock_supply_block ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01one_join_phase ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01optim_inv_only ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01max_merge ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxcpu ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01usedmaxlogqueuecount ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01logqueuecount ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxdatawriter ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxobjgarbagecoll ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxlocks ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01max_retention_time ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxtrans ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxuser ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01maxuserstack ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01mb_data_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01mb_qual_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01mb_stack_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01mb_strat_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01mblock_init (
    tgg00_TransContext    &  source_trans,
    tgg00_MessType_Param     mess_type,
    tgg00_MessType2_Param     mess2_type,
    tgg00_MessBlock       &  mblock);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01min_retention_time ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01mxerrmsg (
    tsp00_Name            &  nam,
    tsp00_Int4               int_wrong,
    tsp00_Int4               int_ok);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01new_dump_page (
    tgg00_VfFileref       &  hostfile,
    tsp00_Page            &  buf,
    tsp00_Int4            &  out_pno,
    integer               &  out_pos,
    tsp00_VfReturn        &  host_err,
    tsp00_ErrText         &  errtext);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01next_prim_number (
    tsp00_Int4            &  prim_int);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01no_of_backup_devs ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01NumberOfUKTs ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_heap_limit ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_heap_usage_threshold ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_stream_timeout ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_vers_free_threshold ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_heap_count ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01oms_heap_blocksize ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01optimize_cache ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01outer_join_ordered ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01packet_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01qual_init (
    tgg00_MessBlock       &  mblock,
    tgg00_QualBufPtr         qual_ptr,
    tsp00_Int4               qual_size);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01BlobPrefetchLowerLimit ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01region_cnt (
    tgg00_RegionType_Param     region_type);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01sm_milliseconds ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01sm_reads ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01sm_selectivity ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01stack_init (
    tgg00_MessBlock       &  mblock,
    tgg00_StackListPtr       stack_ptr,
    tsp00_Int4               stack_size,
    tgg00_QualBufPtr         qual_ptr,
    tsp00_Int4               qual_size);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01stratpart_init (
    tgg00_MessBlock       &  mblock,
    tsp00_MoveObjPtr         stratpart_ptr,
    tsp00_Int4               stratpart_size);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01time_vtrace (
    tgg00_TransContext    &  t,
    tsp00_Name            &  msg,
    tsp00_Int4            &  start_sec,
    tsp00_Int4            &  start_msec);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01trigger ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01use_join_hashtable ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01trans_history_size ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 g01trans_threshold_value ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01userstackoverflow ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01vtr_init ();

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

