/*!******************************************************************************

  @file         hgg04_1.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HGG04_1_H
#define HGG04_1_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x02\x81\x62\x64\x8f\x8e\xf7\xd6\xc4\x51\x93\x34\x87\x1a\xce\xae'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "ggg04.h"
#include "ggg07.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void g04limitprimkeys (
    const tgg00_MessBlock  &  mblock,
    tgg07_ColPosArr       &  startkeyarr,
    tgg00_Lkey            &  start_key,
    tgg07_ColPosArr       &  stopkeyarr,
    tgg00_Lkey            &  stop_key,
    pasbool               &  use_stopkey,
    tsp00_Int2               in_stpos_hint,
    tsp00_Int2               in_value_idx);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04limitprimkeys_subq (
    tgg00_MessBlock       &  mblock,
    tgg04_subq_context    &  subq_context,
    tgg00_Rec             &  value_buf,
    tgg07_ColPosArr       &  startkeyarr,
    tgg00_Lkey            &  start_key,
    tgg07_ColPosArr       &  stopkeyarr,
    tgg00_Lkey            &  stop_key,
    pasbool               &  keys_created,
    pasbool               &  use_stopkey);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04limitinvkeys (
    const tgg00_MessBlock  &  mblock,
    tgg07_StrInvInRange   &  inv_strat,
    tgg00_Lkey            &  startkey,
    tgg00_Lkey            &  stopkey,
    tsp00_Int2               in_stpos_hint,
    tsp00_Int2               in_value_idx);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04limitinvkeys_subq (
    tgg00_MessBlock       &  mblock,
    tgg04_subq_context    &  subq_context,
    tgg00_Rec             &  value_buf,
    tgg07_StrInvInRange   &  inv_strat,
    tgg00_Lkey            &  startkey,
    tgg00_Lkey            &  stopkey,
    pasbool               &  keys_created);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04init_subq_context (
    tgg00_MessBlock       &  mblock,
    tgg07_ColPosArr       &  keyarr,
    tgg04_subq_context    &  subq_context,
    tsp00_Int2               SUBQ_stpos_hint);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04smallest_greater_key_ex (
    tgg00_Lkey            &  key,
    tsp00_Int2               max_length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04greatest_smaller_key_ex (
    tgg00_Lkey            &  key,
    tsp00_Int2               max_length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04smallest_greater_key (
    tgg00_FileId          &  file_id,
    tgg00_Lkey            &  key);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g04greatest_smaller_key (
    tgg00_FileId          &  file_id,
    tgg00_Lkey            &  key);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

