/*!******************************************************************************

  @file         hgg011.h

  ------------------------------------------------------------------------------

  @author       Robin

  @brief        GG_param_functions

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2004-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HGG011_H
#define HGG011_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xc8\xc2\x62\x0b\xb7\x02\x63\x51\xa5\x2f\xf9\xc4\x2c\x16\x92\x02'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void g011register_update_functions ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g011get_conf_param (
    tgg00_BasisError      VAR_VALUE_REF  b_err);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g011get_event_param ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g011get_log_event_param ();

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

