
/*******************************************************************************

  module:       hgg01_1.h

  ------------------------------------------------------------------------------

  responsible:  ElkeZ

  purpose:      Configuration_Parameter

  lastChanged:  2002-12-17

  generatedBy:  $TOOL/bin/ptocProto.py

  ------------------------------------------------------------------------------

  copyright:    Copyright (c) 1999-2005 SAP AG


    ========== licence begin  GPL
    Copyright (c) 1999-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

********************************************************************************/

#ifndef HGG01_1_H
#define HGG01_1_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xd8\xda\x11\x46\x2d\x04\x5e\x8a\x5e\xe4\xf7\x79\xea\x3d\xad\x0b'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "gsp03.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void g01abort (
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text,
    tsp00_Int4               bad_value);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01allocate_msg (
    const char*              msg_label,
    const char*              msg_text,
    tsp00_Int4               alloc_size);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01check (
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text,
    tsp00_Int4               bad_value,
    pasbool                  constraint);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01opaddrmsg (
    tsp3_priority_Param      msg_prio,
    tsp3_msg_type_Param      msg_type,
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text,
    tsp00_Addr               msg_addr);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01opmsg (
    tsp3_priority_Param      msg_prio,
    tsp3_msg_type_Param      msg_type,
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text,
    tsp00_Int4               msg_value);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01optextmsg (
    tsp3_priority_Param      msg_prio,
    tsp3_msg_type_Param      msg_type,
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g01unioptextmsg (
    tsp00_Int4               msg_enc,
    tsp3_priority_Param      msg_prio,
    tsp3_msg_type_Param      msg_type,
    tsp00_Int4               msg_no,
    const char*              msg_label,
    const char*              msg_text);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

