/*!******************************************************************************

  @file         hgg11.h

  ------------------------------------------------------------------------------

  @author       

  @brief        Kernel-Version

\if EMIT_LICENCE  

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HGG11_H
#define HGG11_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x7f\x5c\x14\x61\x68\x13\xcc\xcc\x20\x7e\x67\x14\x1f\xd4\xc5\x5f'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void g11kernel_version (
    tsp00_Version         VAR_ARRAY_REF  vers);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g11ParseVersion (
    tsp00_Version         VAR_ARRAY_REF  vers,
    integer               VAR_VALUE_REF  majorRelease,
    integer               VAR_VALUE_REF  minorRelease,
    integer               VAR_VALUE_REF  correctionLevel,
    integer               VAR_VALUE_REF  buildNumber);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g11ParseExtraNumber (
    tsp00_Version         VAR_ARRAY_REF  vers,
    integer               VAR_VALUE_REF  extraNumber);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

