/*!******************************************************************************

  @file         hgg172.h

  ------------------------------------------------------------------------------

  @author       FerdiF

  @brief        GG_edit_routines

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 1999-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HGG172_H
#define HGG172_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x53\x0b\xaa\xdc\xd9\xf5\x85\x8b\x66\xbc\x52\x7d\x34\xa3\xc4\x09'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "gbd00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void g172fileno_to_line (
    tsp00_C8              VAR_ARRAY_REF  fileno,
    integer               VAR_VALUE_REF  ln_pos,
    char*                                ln);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g172Char8AsUint8_to_line (
    tsp00_C8              VAR_ARRAY_REF  Char8,
    integer               VAR_VALUE_REF  ln_pos,
    char*                                ln);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g172Char8AsInt8_to_line (
    tsp00_C8              VAR_ARRAY_REF  Char8,
    integer               VAR_VALUE_REF  ln_pos,
    char*                                ln);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void g172Sequence_to_line (
    tbd00_LockRequestSeqNo                 high,
    tbd00_LockRequestSeqNo                 low,
    integer               VAR_VALUE_REF  ln_pos,
    char*                                ln);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

