/*!******************************************************************************

  @file         hgg12.h

  ------------------------------------------------------------------------------

  @author       GertG

  @brief        Integer_SET

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2004-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HGG12_H
#define HGG12_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x30\x0e\xad\x27\x08\x3e\x41\x59\x43\xcf\xf2\x76\xde\x9d\x41\x62'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal tsp00_Addr gg12InitBitArray (
    tgg00_TransContext    VAR_VALUE_REF  TransContext,
    tsp00_Int4                           bits);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool gg12GetBit (
    tsp00_Addr                           IntegerSet,
    tsp00_Int4                           number);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void gg12SetBit (
    tsp00_Addr                           IntegerSet,
    tsp00_Int4                           number,
    pasbool                              value);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void gg12FlipBit (
    tsp00_Addr                           IntegerSet,
    tsp00_Int4                           number);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void gg12ClearBitArray (
    tsp00_Addr                           IntegerSet,
    tsp00_Int4                           bits);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void gg12FinalizeBitArray (
    tgg00_TransContext    VAR_VALUE_REF  TransContext,
    tsp00_Addr            VAR_VALUE_REF  IntegerSet);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

