# ::tt/cpan/SAPDB/Istall/xs.mac
#
#    ========== licence begin LGPL
#    Copyright (C) 2002 SAP AG
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    ========== licence end
#


::tt/cpan/SAPDB/Install/zlib.mac
::tt/cpan/SAPDB/Install/zip.mac
::tt/cpan/SAPDB/Install/tool.mac

:tt/cpan/SAPDB/Install/Makefile.PL

:tt/cpan/SAPDB/Install/Jar.pl
:tt/cpan/SAPDB/Install/Jar.xs
:tt/cpan/SAPDB/Install/Jar.def
:tt/cpan/SAPDB/Install/Jar.exp
:tt/cpan/SAPDB/Install/Jar.pm

:tt/cpan/SAPDB/Install/SysInfo.pl
:tt/cpan/SAPDB/Install/SysInfo.xs
:tt/cpan/SAPDB/Install/SysInfo.def
:tt/cpan/SAPDB/Install/SysInfo.exp
:tt/cpan/SAPDB/Install/SysInfo.pm

:tt/cpan/SAPDB/Install/PipeExec.pl
:tt/cpan/SAPDB/Install/PipeExec.xs
:tt/cpan/SAPDB/Install/PipeExec.def
:tt/cpan/SAPDB/Install/PipeExec.exp
:tt/cpan/SAPDB/Install/PipeExec.pm


:tt/cpan/SAPDB/Install/ProcState.xs
:tt/cpan/SAPDB/Install/ProcState.def
:tt/cpan/SAPDB/Install/ProcState.pm
:tt/cpan/SAPDB/Install/ProcState.exp

&if $OS == UNIX
!!cd $WRK/fast/obj/tt/cpan/SAPDB/Install; $TOOLSHELL Makefile.PL; make install
&endif
&if $OS == WIN32
!!cd %wrk%\fast\obj\tt\cpan\SAPDB\Install && \
 %TOOLSHELL% Makefile.PL && \
 nmake && \
 nmake install
&endif
