#
# ::tt/cpan/SAPDB/Install/zlib.mac
#
#
#    ========== licence begin LGPL
#    Copyright (C) 2002 SAP AG
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    ========== licence end
#


:tt/cpan/SAPDB/Install/zlib/zconf.h
:tt/cpan/SAPDB/Install/zlib/zlib.h
:tt/cpan/SAPDB/Install/zlib/deflate.h
:tt/cpan/SAPDB/Install/zlib/infblock.h
:tt/cpan/SAPDB/Install/zlib/infcodes.h
:tt/cpan/SAPDB/Install/zlib/inffast.h
:tt/cpan/SAPDB/Install/zlib/inffixed.h
:tt/cpan/SAPDB/Install/zlib/inftrees.h
:tt/cpan/SAPDB/Install/zlib/infutil.h
:tt/cpan/SAPDB/Install/zlib/trees.h
:tt/cpan/SAPDB/Install/zlib/zconf.h
:tt/cpan/SAPDB/Install/zlib/zutil.h
:tt/cpan/SAPDB/Install/zlib/adler32.c
:tt/cpan/SAPDB/Install/zlib/compress.c
:tt/cpan/SAPDB/Install/zlib/crc32.c
:tt/cpan/SAPDB/Install/zlib/deflate.c
:tt/cpan/SAPDB/Install/zlib/gzio.c
:tt/cpan/SAPDB/Install/zlib/infblock.c
:tt/cpan/SAPDB/Install/zlib/infcodes.c
:tt/cpan/SAPDB/Install/zlib/inffast.c
:tt/cpan/SAPDB/Install/zlib/inflate.c
:tt/cpan/SAPDB/Install/zlib/inftrees.c
:tt/cpan/SAPDB/Install/zlib/infutil.c
:tt/cpan/SAPDB/Install/zlib/trees.c
:tt/cpan/SAPDB/Install/zlib/uncompr.c
:tt/cpan/SAPDB/Install/zlib/zutil.c
:tt/cpan/SAPDB/Install/zlib/Makefile.PL
:tt/cpan/SAPDB/Install/zlib/Makefile.w32
:tt/cpan/SAPDB/Install/zlib/Makefile.w64

