(*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*)
(* p2cstdf.inc                               *)
(*                                           *)
(* function declarations required by GNU p2c *)
(*=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=*)

FUNCTION odd (i : integer) : integer; EXTERN;
FUNCTION sqrt (r : real) : real; EXTERN;
FUNCTION sqrt (r : real) : real; EXTERN;
FUNCTION trunc (r : real) : integer; EXTERN;
