# vmake.mac
#
#    ========== licence begin LGPL
#    Copyright (C) 2002 SAP AG
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    ========== licence end
#

? default layer : APODev/profiles

&if $OSSPEC = OSF1
iprofile.alphaosf
&elif $OSSPEC = AIX
iprofile.rs6000_51_64
iprofile.rs6000_64
&elif $MACH = SUN
iprofile.sun_64
&elif $OSSPEC == SOLARIS
&  if $MACH == SPARC
iprofile.sun_64
&  elif $MACH == X86_64
iprofile.sunx86_64
&  endif
&elif $OSSPEC = LINUX
iprofile.linuxintel
iprofile.linuxia64
iprofile.linuxia64sles9
iprofile.linuxx86_64
iprofile.linuxppc64
&elif $OSSPEC = HPUX
iprofile.hp_64
iprofile.hpia64
&endif

