
&if not defined SAPDB_MAKE_LOCATION
? propagate: SAPDB_MAKE_LOCATION=wdf
&endif
&if not variant(nobuild)
:MakeTools/RemoteMake/webmake/Server/apache/httpd_2.0.52.tar.gz
!! cd $TOOL/src/apache; gzip -d httpd_2.0.52.tar.gz ; tar -xvf httpd_2.0.52.tar; cd httpd-2.0.52 ; ./configure --prefix=/devtool/local/apache; make; make install
&endif
:MakeTools/RemoteMake/webmake/Server/config/httpd.conf
:MakeTools/RemoteMake/webmake/Server/cgicall4.pl

