#    ========== licence begin  GPL
#    Copyright (c) 2003-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end
&ifvar gen
testbincompat.lnk
&if $OS=WIN32
!!perl %OWN%/tool/bin/genbincompattest.pl create %OWN%
&else
!!(echo "Only supported on Windows" && false)
&endif
&else
sqldbc-noinst.mac
testbincompat.lnk
bincompat.mk
#testbincompat
testbincompat_102723.cpp ascii 
testbincompat_102710.cpp ascii 
testbincompat_98781.cpp ascii 
testbincompat_98304.cpp ascii 
testbincompat_92146.cpp ascii 
testbincompat_92742.cpp ascii 
testbincompat_92168.cpp ascii 
testbincompat_89660.cpp ascii 
&if $OS = WIN32
!!(cd %OWN%\test\sqldbc && \
  nmake SQLDBCSDK=%OWN%\usr -f bincompat.mk clean all)
&else
!!(cd $OWN/test/sqldbc && \
   make SQLDBCSDK=$OWN/usr -f bincompat.mk clean all)
&endif
&endif