#
#    ========== licence begin  GPL
#    Copyright (c) 2003-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

::SAPDB/Interfaces/SQLDBC/default.mac
:SAPDB/Interfaces/tools/setenv.sh
allsqldbc.lnk
allsqldbc_c.lnk
applinfo.lnk
canceltest.lnk
datatrunc.lnk
emptystring.lnk
unterm.lnk
rowsetnav.lnk
convertUCS2.lnk
allresultset.lnk
allrowset.lnk
droptables.lnk
helloWorld.lnk
SQLStmt.lnk
sqlmode.lnk
ParamBind.lnk
paramtypes.lnk
piecewise.lnk
lcsqldbctest.lnk
lobselectinto.lnk
lobposition.lnk
blobsingleinsert.lnk
rowsaffected.lnk
multiplefetch.lnk
resultSetGetObject.lnk
resultSetBindColumn.lnk
errorCheck.lnk
typesCheck.lnk
typestest.lnk
batchtest.lnk
oranull.lnk
conProp.lnk
PreparedStatement.lnk
connecttest.lnk
oomtest.lnk
loblocatortest.lnk
ptsmisc.lnk
longmix.lnk
commandinfo.lnk
resultsetmetadata.lnk
lastserial.lnk
signalaction.lnk
prepstmtmetadata.lnk
truncnames.lnk
typesindicator.lnk
odbcbinhex.lnk
closehandlesonexit.lnk
profilecountertest.lnk
typestestunicode.lnk
bincompat.mac
