/*!******************************************************************************

  @file         hbd09.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HBD09_H
#define HBD09_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x55\xae\xbc\x3a\x2a\xce\x73\xe4\xc7\x1b\xee\xa8\x16\xfc\xd2\x3b'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void bd09FinishLoad (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  file_id,
    tsp00_PageNo                         rightmost_leaf);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09GetNextLong (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  file_id,
    integer                              string_col_cnt,
    tgg00_Lkey            VAR_VALUE_REF  rk,
    integer               VAR_VALUE_REF  string_col_no,
    tgg00_FileId          VAR_VALUE_REF  col_id,
    tgg00_FilePos         VAR_VALUE_REF  file_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09InitLoad (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  file_id,
    pasbool                              set_read_only,
    tsp00_PageNo          VAR_VALUE_REF  rightmost_leaf);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09InitUnload (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  file_id);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09LoadTable (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  tree_id,
    tsp00_PageNo          VAR_VALUE_REF  rightmost_leaf,
    tsp00_PageNo          VAR_VALUE_REF  check_leaf,
    tgg00_Surrogate       VAR_ARRAY_REF  lobParentFileNo,
    tsp00_Int4                           load_buf_len,
    void                  *  load_buf);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09ReorgTreeIndex (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  file_id,
    tgg00_Lkey            VAR_VALUE_REF  rk);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd09UnloadTable (
    tgg00_TransContext    VAR_VALUE_REF  t,
    tgg00_FileId          VAR_VALUE_REF  tree_id,
    tsp00_PageNo          VAR_VALUE_REF  pno,
    tsp00_PageNo          VAR_VALUE_REF  pno_x,
    tsp00_Int4                           ret_buf_size,
    void                  *  ret_buf,
    tsp00_Int4            VAR_VALUE_REF  ret_buf_len);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

