/*!******************************************************************************

  @file         hbd06_1.h

  ------------------------------------------------------------------------------

  @author       JuergenP

  @brief        error_text_handling

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HBD06_1_H
#define HBD06_1_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x9a\xbf\x96\x6e\x81\xb1\xc3\xb9\xbd\xd9\x59\x6b\x72\xb1\x34\xc2'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void bd06IllegalRootAccess (
    tgg00_TransContext    &  trans,
    tgg00_FileId          &  fileId,
    pasbool                  bWriteBacktrace);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

