/*!******************************************************************************

  @file         hbd360.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HBD360_H
#define HBD360_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xd3\x02\x09\xa4\x80\x32\xf4\x78\xc8\x3f\x0c\x70\x26\xa0\x40\x22'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "gbd00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void bd360NextQualifiedRecordFromTree (
    tbd_current_tree      VAR_VALUE_REF  current,
    tsp00_KeyPtr                         pCurrRecKey,
    SAPDB_Int2            VAR_VALUE_REF  currRecKeyLen,
    const tsp00_KeyPtr                   pStopKey,
    const SAPDB_Int2                     stopKeyLen,
    tgg00_Lkey            VAR_VALUE_REF  lockKey,
    const SAPDB_Int4                     recBufferSize,
    tsp00_MoveObjPtr                     pRecBuffer,
    SAPDB_Int4            VAR_VALUE_REF  recBufferPos,
    tgg00_SelectFieldsParam  VAR_VALUE_REF  sel,
    tgg00_StackDesc       VAR_VALUE_REF  stackDesc,
    SAPDB_Int4            VAR_VALUE_REF  currResultCnt,
    pasbool               VAR_VALUE_REF  bIsNotQualified,
    pasbool               VAR_VALUE_REF  bDoRemoveSQLLock,
    tgg00_LockReqMode     VAR_VALUE_REF  grantedLock,
    tsp00_PageNo          VAR_VALUE_REF  unlockedPageNo);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void bd360PrevQualifiedRecordFromTree (
    tbd_current_tree      VAR_VALUE_REF  current,
    tsp00_KeyPtr                         pCurrRecKey,
    SAPDB_Int2            VAR_VALUE_REF  currRecKeyLen,
    const tsp00_KeyPtr                   pStopKey,
    const SAPDB_Int2                     stopKeyLen,
    tgg00_Lkey            VAR_VALUE_REF  lockKey,
    const SAPDB_Int4                     recBufferSize,
    tsp00_MoveObjPtr                     pRecBuffer,
    SAPDB_Int4            VAR_VALUE_REF  recBufferPos,
    tgg00_SelectFieldsParam  VAR_VALUE_REF  sel,
    tgg00_StackDesc       VAR_VALUE_REF  stackDesc,
    SAPDB_Int4            VAR_VALUE_REF  currResultCnt,
    pasbool               VAR_VALUE_REF  bIsNotQualified,
    pasbool               VAR_VALUE_REF  bDoRemoveSQLLock,
    tgg00_LockReqMode     VAR_VALUE_REF  grantedLock,
    tsp00_PageNo          VAR_VALUE_REF  unlockedPageNo);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

