/*!******************************************************************************

  @file         hak071.h

  ------------------------------------------------------------------------------

  @author       ElkeZ

  @brief        AK_error_handling

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK071_H
#define HAK071_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x6a\xd2\xa8\xec\x1c\x77\x6a\xfa\xe6\xb2\x3d\x86\x4c\xc8\x78\xf6'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal tsp00_Int2 a071_return_code (
    tgg00_BasisError                     b_err,
    tsp00_SqlMode_Param                  sqlmode);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a071_getmessagetext (
    tsp00_Int2                           msgno,
    char*                                msgbuf,
    tsp00_Int2            VAR_VALUE_REF  msglen,
    pasbool               VAR_VALUE_REF  found);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a071_nextmessagetext (
    tsp00_Int2            VAR_VALUE_REF  msgno,
    char*                                msgbuf,
    tsp00_Int2            VAR_VALUE_REF  msglen,
    pasbool               VAR_VALUE_REF  found);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

