/*!******************************************************************************

  @file         hak362.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 1999-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HAK362_H
#define HAK362_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x43\x53\xdb\xde\xca\x75\x79\xf6\x7b\xc7\xe1\x34\x4d\x67\x95\xb2'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "vak001.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal tsp00_TaskId a362OnlineTaskId;

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a362migrate (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    pasbool               VAR_VALUE_REF  in_warm_session);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a362AuthorizationConvertPasswords (
    tak_userrecord        VAR_VALUE_REF  authorization,
    tgg00_BasisError      VAR_VALUE_REF  e);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a362SetUserAndSchema (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tsp00_KnlIdentifier   VAR_ARRAY_REF  userName,
    tgg00_Surrogate       VAR_ARRAY_REF  userId,
    tgg00_Surrogate       VAR_ARRAY_REF  schemaId,
    tak_user_info         VAR_VALUE_REF  userInfo);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

