/*!******************************************************************************

  @file         hak728.h

  ------------------------------------------------------------------------------

  @author       GertG / HolgerB

  @brief        Strategy_Explain

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK728_H
#define HAK728_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x03\xc5\x98\x33\x40\x43\x17\xad\x90\x43\x23\x07\x9d\x18\xa3\x6c'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "vak001.h"
#include "ggg07.h"
#include "gak68.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void a728_init_strat_texts ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a728_explain (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_dml_info          VAR_VALUE_REF  dmli,
    tgg07_StrategyInfo    VAR_VALUE_REF  gg_strategy,
    tak68_join_ptr                       joininfo_ptr,
    void                  *  morestratbuf,
    tsp00_Int4                           morestratbufsize,
    tsp00_Int4                           morestratpos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a728explain_no_join_strat_now (
    tak_all_command_glob  VAR_VALUE_REF  acv);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

