# -----------------------------------------------------------------------------
# module:    docu.mac
#
# responsible: DL_SAP_DB_INTERFACES
#
# special area: Makes the doc for the Interface Runtime Library
# description:
#
# see:
#
# change history:
# -----------------------------------------------------------------------------
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

# Documentation will only be generated on Windows
#
# For other OS check if the demo world compiles.
#
::SAPDB/Samples/SQLDBC/SQLDBCsamples.mac

&if defined SAPDB_INTERNAL

&if $OSSPEC in [ WIN32, LINUX ]  && $MACH = I386
SQLDBC.h
SQLDBC-sqldbc_c.h
SQLDBC_Types.h
SQLDBC_IRuntime.h
&if $OSSPEC in [ WIN32 ]  && (!($MACH == i386 && defined BIT64 && !defined XCOMP))
:redist/bin/I386_WIN32/doxygen.exe
&endif
&if $OSSPEC in [ LINUX ]  && (!($MACH == i386 && defined BIT64 && !defined XCOMP))
:redist/bin/I386_LINUX_32/doxygen
&endif
:SAPDB/Interfaces/SQLDBC/genSQLDBCdoc.pl
:SAPDB/Interfaces/SQLDBC/main.dxy

:SAPDB/Interfaces/SQLDBC/license-FLOSS.dxy
SQLDBC-FLOSS.doxygen

:SAPDB/Interfaces/SQLDBC/install.dxy
:SAPDB/Interfaces/Runtime/IFR_ErrorHndl-doxygen.cpp

:SAPDB/Interfaces/doc/ifr.txt         ascii ->$WRK/fast/doc/SAPDB/Interfaces/doc/ifr.txt         nocomfile
:SAPDB/Interfaces/doc/html_header.txt ascii ->$WRK/fast/doc/SAPDB/Interfaces/doc/html_header.txt nocomfile
:SAPDB/Interfaces/doc/html_footer.txt ascii ->$WRK/fast/doc/SAPDB/Interfaces/doc/html_footer.txt nocomfile
:SAPDB/Interfaces/doc/doxygen.css     ascii ->$WRK/fast/doc/SAPDB/Interfaces/doc/doxygen.css     nocomfile
:SAPDB/Interfaces/doc/SQLDBC_Architecture.gif     binary ->$WRK/fast/doc/SAPDB/Interfaces/doc/SQLDBC_Architecture.gif     nocomfile
&if $OSSPEC = LINUX
!(perl $OWN/tool/bin/genSQLDBCdoc.pl --with-floss --dir=$OWN/usr/sdk/sqldbc/doc/html --addfiles=etc/SQLDBCsamples.lst)
&else
!(perl %OWN%\tool\bin\genSQLDBCdoc.pl --with-floss --dir=%OWN%\usr\sdk\sqldbc\doc\html --addfiles=etc/SQLDBCsamples.lst)
&endif
&endif

&endif

