#
#
#    ========== licence begin  GPL
#    Copyright (c) 2003-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

::SAPDB/Samples/SQLDBC/HelloWorld/HelloWorld.mac
::SAPDB/Samples/SQLDBC/UNICODE/UNICODE.mac
::SAPDB/Samples/SQLDBC/LOB/LOB.mac
!imf -F ::SAPDB/Samples/SQLDBC/SQLDBCsamples.mac
&if $OS = WIN32
&if !($MACH == I386 && defined BIT64 && !defined XCOMP)
!(cd %INSTROOT% && tar -cvozf maxdb-samples-sqldbc.tgz -T %INSTROOT%\etc\SQLDBCsamples.lst )
&endif
&else
&if $OSSPEC == LINUX
!(cd $INSTROOT && tar -cvozf maxdb-samples-sqldbc.tgz -T etc/SQLDBCsamples.lst )
&else
!(cd $INSTROOT && gtar -cvozf maxdb-samples-sqldbc.tgz -T etc/SQLDBCsamples.lst )
&endif
&endif

