/*!******************************************************************************

  @file         hsp20.h

  ------------------------------------------------------------------------------

  @author       

  @brief        RTE-Extension-20

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HSP20_H
#define HSP20_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x03\x78\xce\x10\xa1\x14\x22\x9d\x87\xa2\x93\x50\x4f\xfb\x7d\x60'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void s20int4_to_buf (
    tsp00_Int4               val,
    void                  *  destin,
    tsp00_Int4               destin_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20int4_to_buf_1 (
    tsp00_Int4               val,
    void                  *  destin,
    tsp00_Int4               destin_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20int4_to_buf_2 (
    tsp00_Int4               val,
    void                  *  destin,
    tsp00_Int4               destin_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20int4_to_buf_3 (
    tsp00_Int4               val,
    void                  *  destin,
    tsp00_Int4               destin_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20int4_to_buf_swap (
    tsp00_Int4               val,
    tsp00_SwapKind_Param     source_swap,
    void                  *  destin,
    tsp00_Int4               destin_pos,
    tsp00_SwapKind_Param     destin_swap);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20int4_to_buf_swap_1 (
    tsp00_Int4               val,
    tsp00_SwapKind_Param     source_swap,
    void                  *  destin,
    tsp00_Int4               destin_pos,
    tsp00_SwapKind_Param     destin_swap);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s20buf_to_int4 (
    void                  *  source,
    tsp00_Int4               source_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s20buf_to_int4_1 (
    void                  *  source,
    tsp00_Int4               source_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s20buf_to_int4_2 (
    void                  *  source,
    tsp00_Int4               source_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s20buf_to_int4_swap (
    void                  *  source,
    tsp00_Int4               source_pos,
    tsp00_SwapKind_Param     source_swap,
    tsp00_SwapKind_Param     destin_swap);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int2 s20int4_to_int2 (
    tsp00_Int4               i4);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s20swap_int4 (
    tsp00_Int4            &  val,
    tsp00_SwapKind_Param     source_swap,
    tsp00_SwapKind_Param     destin_swap);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

