
/*******************************************************************************

  module:       hsp30.h

  ------------------------------------------------------------------------------

  responsible:  

  purpose:      RTE-Extension-30

  lastChanged:  2002-12-16

  generatedBy:  $TOOL/bin/ptocProto.py

  ------------------------------------------------------------------------------

  copyright:    Copyright (c) 1999-2005 SAP AG



    ========== licence begin  GPL
    Copyright (c) 1999-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end



********************************************************************************/

#ifndef HSP30_H
#define HSP30_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xdf\x58\x8c\x4a\xb9\xee\xcd\x24\x10\x66\xf7\x5a\x72\x9a\x9d\xcf'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void s30cmp (
    const void*                          buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    const void*                          buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30cmp1 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30cmp2 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30cmp3 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30gkey (
    void                  *  buf,
    integer                              pos,
    integer                              length,
    tsp00_Key             VAR_ARRAY_REF  k);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool s30eq (
    const void*                          a,
    const void*                          b,
    tsp00_Int4                           b_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool s30eq1 (
    void                  *  a,
    void                  *  b,
    tsp00_Int4                           b_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool s30eqkey (
    tsp00_Sname           VAR_ARRAY_REF  a,
    void                  *  b,
    tsp00_Int4                           b_pos,
    integer                              length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal integer s30klen (
    const void*                          str,
    char                                 val,
    integer                              cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30lnr (
    const void*                          str,
    char                                 skip_val,
    tsp00_Int4                           start_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30lnr1 (
    void                  *  str,
    char                                 skip_val,
    tsp00_Int4                           start_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30lnr_defbyte (
    const void*                          str,
    char                                 defbyte,
    tsp00_Int4                           start_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30nlen (
    const void*                          str,
    char                                 val,
    tsp00_Int4                           start,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30len (
    const void*                          str,
    char                                 val,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30len1 (
    void                  *  str,
    char                                 val,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30len2 (
    void                  *  str,
    char                                 val,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30len3 (
    void                  *  str,
    char                                 val,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30len4 (
    void                  *  str,
    char                                 val,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30map (
    tsp00_Ctable          VAR_ARRAY_REF  code_t,
    const void*                          source,
    tsp00_Int4                           source_pos,
    void                  *  destin,
    tsp00_Int4                           destin_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30luc (
    const void*                          buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    const void*                          buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30luc1 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30lcm (
    const void*                          buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    const void*                          buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30lcm1 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30lcm2 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30lcm3 (
    void                  *  buf1,
    tsp00_Int4                           fieldpos1,
    tsp00_Int4                           fieldlength1,
    void                  *  buf2,
    tsp00_Int4                           fieldpos2,
    tsp00_Int4                           fieldlength2,
    tsp00_LcompResult     VAR_VALUE_REF  l_result);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30lenl (
    const void*                          str,
    char                                 val,
    tsp00_Int4                           start,
    tsp00_Int4                           cnt);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad1 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad2 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad3 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad4 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad5 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad6 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Addr s30gad7 (
    void                  *  b);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 s30unilnr (
    const void*                          str,
    tsp00_C2              VAR_ARRAY_REF  skip_val,
    tsp00_Int4                           start_pos,
    tsp00_Int4                           length);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30xorc4 (
    tsp00_C4              VAR_ARRAY_REF  c4_1,
    tsp00_C4              VAR_ARRAY_REF  c4_2,
    tsp00_C4              VAR_ARRAY_REF  c4_target);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s30surrogate_incr (
    tsp00_C8              VAR_ARRAY_REF  surrogate);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

