#  @(#)loadertest.mac     
#
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

:SAPDB/Scripting/Resource/loaderdoc/demo/transport.py
:SAPDB/Scripting/Resource/loaderdoc/demo/loader.cfg
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_1.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_2.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_3.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_4.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_5.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_6.TXT
:SAPDB/Scripting/Resource/loaderdoc/demo/ISO_8859_7.TXT
:SAPDB/Scripting/Resource/loaderdoc/test/transport.par
:SAPDB/Scripting/Resource/loaderdoc/test/transport.cfg
# loadertest.lst
::SAPDB/Scripting/Resource/davdoc/davdoc.mac
::SAPDB/Scripting/Resource/dbmdoc/dbmdoc.mac
::SAPDB/Scripting/Resource/loaderdoc/loaderdoc.mac
&if $OS in [ WIN32 ]
  :SAPDB/Scripting/Resource/loadertest.lst      ->$WRK/config/loadertest.lst ascii 
!!SAPCAR -c -T ../../config/loadertest.lst      -f ../../../../test/tr_loader.sar -C ../../../../test -v
&else
  :SAPDB/Scripting/Resource/loadertest_unix.lst ->$WRK/config/loadertest_unix.lst ascii 
!!SAPCAR -c -T ../../config/loadertest_unix.lst -f ../../../../test/tr_loader.sar -C ../../../../test -v
&endif

# SAPCAR -xvf tr_loader.sar

