#
#    ========== licence begin  GPL
#    Copyright (c) 2003-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

# generate files for package
#
LongGetObject.cpp ascii distrib
LongPutData.cpp ascii distrib
Makefile ascii concom=yes distrib
&if $OS = WIN32
!(cd %INSTROOT%\samples\SQLDBC\LOB && \
&if $MACH == AMD64
  nmake SQLDBCSDK=%OWN%\usr amd64 )
&else
  nmake SQLDBCSDK=%OWN%\usr win32 )
&endif
&else
!(cd $INSTROOT/samples/SQLDBC/LOB && \
&if $MACH == SUN
  make SQLDBCSDK=$OWN/usr sun )
&endif
&if $OSSPEC == SOLARIS
&if $MACH == SPARC
  make SQLDBCSDK=$OWN/usr sun )
&elif $MACH == X86_64
  make SQLDBCSDK=$OWN/usr sunx86_64 )
&elif $MACH == I386
  make SQLDBCSDK=$OWN/usr sunx86 )
&endif
&elif $OSSPEC = AIX
  make SQLDBCSDK=$OWN/usr aix )
&elif $OSSPEC = HPUX
&if $MACH = HP_IA64
  make SQLDBCSDK=$OWN/usr hpIa64 )
&else
  make SQLDBCSDK=$OWN/usr hpux )
&endif
&elif $OSSPEC = OSF1
  make SQLDBCSDK=$OWN/usr dec )
&elif $OSSPEC = LINUX
&if $MACH = SDBonPPC64
  make SQLDBCSDK=$OWN/usr linuxppc )
&else
  make SQLDBCSDK=$OWN/usr linux )
&endif
&endif
&endif
