# Script to create a database
# Logon to the system
user_system remuser,Remuser

# some info
dbm_version
db_enum

# create the upc file
db_create TESTDB dbm,dbm remuser,Remuser

# change the user to database manager
user_logon dbm,dbm

# create the db parameter
param_startsession 
param_init LVC
param_put MAXUSERTASKS 5 
param_checkall 
param_commitsession 
param_addvolume 1 LOG LOG_001 F 2000 
param_addvolume 1 DATA DAT_001 F 5000 
db_admin 
db_activate dba,dba
load_systab -ud dba

# shut down the db
db_offline

# start the db
db_online

# create backup media

# complete backup into file
medium_put completeF complete FILE DATA 0 0 YES
# auto-log to file
medium_put autosave autolog FILE AUTO

# create user for SQL test
user_create upgtst,upgtst DBA
