# Script to create a database
# Logon to the system
user_system remuser,Remuser

# create the upc file
db_create TESTDB dbm,dbm remuser,Remuser

# change the user to database manager
user_logon dbm,dbm

# create the db parameter
param_startsession
param_init OLTP
# for the loader, just in case
param_put MAXLOCKS 12000
# We don't really want 20 processes in mem
param_put MAXUSERTASKS 5
param_checkall
param_commitsession
param_abortsession

# add the devspaces
# We need at least 200 MB space for the R3 schema
param_adddevspace 1 DATA data_001 F 30000
param_adddevspace 1 LOG log_001 F 10000

## Backup medium where we get our schema from
medium_put completeF /tmp/litendian/complete-74 FILE DATA 0 0 YES

# set the db in admin status   -> in new version db_admin
db_cold

# connect to the util session and initialized/format the devspaces
util_connect
util_execute init config

## RESTORE
recover_start completeF DATA
util_release

# shut down the db
db_offline

# start the db
db_warm

# load the system tables. Password domain must be used on the first run
load_systab -u dba,dba -ud dba

# create backup media

# complete backup into file
# auto-log to file
medium_put autosave autolog FILE AUTO
