# Script to create a database
# Logon to the system
user_system remuser,Remuser

# some info
dbm_version
db_enum

# create the upc file
db_create TESTDB dbm,dbm remuser,Remuser

# change the user to database manager
user_logon dbm,dbm

# create the db parameter
param_startsession
param_init LVC
param_checkall
param_commitsession
param_abortsession

# add the devspaces
param_adddevspace 1 DATA data_001 F 5000
param_adddevspace 1 LOG log_001 F 5000


# set the db in admin status   -> in new version db_admin
db_cold

# connect to the util session and initialized/format the devspaces
util_connect
util_execute init config
util_activate dba,dba
util_release

# load the system tables. Password domain must be used on the first run
load_systab -ud dba

# shut down the db
db_offline

# start the db
db_warm

# create backup media

# complete backup into file
medium_put completeF complete FILE DATA 0 0 YES
# auto-log to file
medium_put autosave autolog FILE AUTO

# change the user to the database admin
user_logon dba,dba
