# Script to fake a backup of the liveCache
# This is needed to trick the installer to believe the liveCache had been
# backuped, otherwise it wont update the DB
user_logon dbm,dbm

sql_connect dba,dba
sql_execute CREATE TABLE "__$__LCFLAG" (begin DATE, end DATE, version INT, flag CHAR(1))
sql_execute INSERT INTO "__$__LCFLAG" (flag) VALUES ('X')
sql_execute GRANT SELECT ON "__$__LCFLAG" TO PUBLIC
sql_release
