/*!******************************************************************************

  @file         hak545.h

  ------------------------------------------------------------------------------

  @author       GertG

  @brief        diagnose_monitor

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK545_H
#define HAK545_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x77\xe3\x51\xc1\xce\x48\xba\x05\x59\x63\x78\xe6\xee\xf9\xaa\x37'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "vak001.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void a545_init ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545diag_monitor_syntax (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tsp00_Int2            VAR_VALUE_REF  put_node);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545sm_data_tree (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tgg00_FileId          VAR_VALUE_REF  mondata_tree);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545sm_insert (
    tak_all_command_glob  VAR_VALUE_REF  acv);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545sm_param_info (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_parsid            VAR_VALUE_REF  parsid);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545sm_reset (
    tgg00_FileId          VAR_VALUE_REF  monitor_tree);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545sm_set_rowno (
    tsp00_Int4                           maxrowno);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 a545sm_get_rowno ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545diag_parse_info (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_parsid            VAR_VALUE_REF  parsid,
    tak_parsid            VAR_VALUE_REF  sel_parsid);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a545clear_monitor (
    tak_all_command_glob  VAR_VALUE_REF  acv);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

