/*!******************************************************************************

  @file         hak509.h

  ------------------------------------------------------------------------------

  @author       ElkeZ

  @brief        Pseudo_fieldmap

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK509_H
#define HAK509_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x22\x8a\xc6\xf2\xe8\x4b\xe0\xda\x7a\x0e\x67\x34\x8f\x47\x0a\x47'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal tsp00_Int4 a509size_of_map ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool a509append_value (
    tsp00_MoveObjPtr                     map_ptr,
    tsp00_MoveObjPtr                     databuffer_ptr,
    tsp00_Int4                           databuffer_length,
    tsp00_Int4                           value_pos);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool a509build_map_from_databuffer (
    tsp00_MoveObjPtr                     databuffer_ptr,
    tsp00_MoveObjPtr                     map_ptr,
    tsp00_Int4            VAR_VALUE_REF  length_in_databuffer);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool a509get_one_value (
    tsp00_MoveObjPtr                     map_ptr,
    tsp00_Int2                           value_no,
    tsp00_MoveObjPtr      VAR_VALUE_REF  value_ptr,
    tsp00_Int4            VAR_VALUE_REF  value_len,
    pasbool               VAR_VALUE_REF  is_null,
    pasbool               VAR_VALUE_REF  is_default);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 a509get_datapos (
    tsp00_MoveObjPtr                     map_ptr,
    tsp00_Int2                           value_no);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool a509is_long_value (
    tsp00_MoveObjPtr                     map_ptr,
    integer                              value_no);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a509reset_value_map (
    tsp00_MoveObjPtr                     map_ptr);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a509set_value_to_null (
    tsp00_MoveObjPtr                     map_ptr,
    integer                              value_no);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a509set_long_value (
    tsp00_MoveObjPtr                     map_ptr,
    integer                              value_no);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int2 a509value_cnt (
    tsp00_MoveObjPtr                     map_ptr);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

