/*!******************************************************************************

  @file         hak502.h

  ------------------------------------------------------------------------------

  @author       ElkeZ

  @brief        Executing_complex

\if EMIT_LICENCE  

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK502_H
#define HAK502_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xd9\x63\x44\x21\x4a\x55\x20\xa3\x16\xea\xb8\xec\x7a\x88\x12\x86'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "ggg00.h"
#include "vak001.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void a502complex_execution (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_dml_info          VAR_VALUE_REF  dmli,
    tak_changerecord      VAR_VALUE_REF  change_rec,
    tak_parskey           VAR_VALUE_REF  parsk,
    pasbool                              output_during_execution);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a502correlation_execute (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_dml_info          VAR_VALUE_REF  dmli,
    tak_changerecord      VAR_VALUE_REF  change_rec,
    tak_exec_rec          VAR_VALUE_REF  erec,
    tak_parskey           VAR_VALUE_REF  parsk,
    tak_corr_infos        VAR_VALUE_REF  old_cinfo,
    pasbool                              inner_loop);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a502destroy_file (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tgg00_FileId          VAR_VALUE_REF  tree);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a502empty_result (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_dml_info          VAR_VALUE_REF  dmli,
    tgg00_FileId          VAR_VALUE_REF  res_tree);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

