/*!******************************************************************************

  @file         hak720.h

  ------------------------------------------------------------------------------

  @author       GertG / HolgerB

  @brief        Build_Strategy_Decision

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HAK720_H
#define HAK720_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x8a\xc2\x14\x21\x5f\x1d\xcc\x58\xb4\x5b\xd3\xdf\xae\xea\x4e\xc4'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "gak00.h"
#include "vak001.h"
#include "ggg07.h"
#include "gak70.h"
#include "gak71.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void a720strategy_decision (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_syspointerarr     VAR_VALUE_REF  sparr,
    tak70_strategy_record  VAR_VALUE_REF  access_info,
    tgg07_StrategyInfo    VAR_VALUE_REF  gg_strategy,
    tak70_one_strat       VAR_VALUE_REF  chosen_strat,
    tak00_ord_fields      VAR_VALUE_REF  order_fields,
    tsp00_Int2            VAR_VALUE_REF  StratInfo_len,
    pasbool                              call_for_L1);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a720decide_L2_range (
    tak_all_command_glob  VAR_VALUE_REF  acv,
    tak_syspointerarr     VAR_VALUE_REF  sparr,
    tak70_strategy_record  VAR_VALUE_REF  access_info,
    tgg07_StrategyInfo    VAR_VALUE_REF  gg_strategy,
    tsp00_Int2            VAR_VALUE_REF  StratInfo_len,
    tak71_page_eval_rec   VAR_VALUE_REF  eval_info,
    tsp00_Int4                           L1_pageIO,
    tsp00_Longreal        VAR_VALUE_REF  L1_stratvalue,
    tgg07_StrKeyInRange   VAR_VALUE_REF  key_range);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a720glob_init_eval_stat ();

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

