/*!******************************************************************************

  @file         hak99.h

  ------------------------------------------------------------------------------

  @author       

  @brief        Syntax-Tree-Printer

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HAK99_H
#define HAK99_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xee\xf5\x49\x95\xb6\x77\x32\x85\xe8\xec\xf4\xde\xb9\x58\x2d\xa5'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "gak00.h"
#include "vak001.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal tsp00_Line a99blankline;

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99init ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99priv (
    tgg00_Debug_Param                    layer,
    tak_privilege                        p,
    tsp00_C18             VAR_ARRAY_REF  id,
    pasbool                              unpacked);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99_priv_all_set (
    tgg00_Debug_Param                    layer,
    tak00_PrivilegeSet    VAR_ARRAY_REF  priv_all_set,
    tak00_PrivilegeSet    VAR_ARRAY_REF  priv_all_grant_set);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99putint (
    tsp00_DataLine        VAR_VALUE_REF  lineinfo,
    integer                              integervalue,
    tsp00_FieldRange                     fieldlength);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99put4int (
    tsp00_DataLine        VAR_VALUE_REF  data,
    tsp00_Int4                           i,
    tsp00_FieldRange                     fl);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void a99print_nodes (
    tak_ap_max_tree       VAR_ARRAY_REF  ap_tree,
    integer                              cntnodes,
    tsp00_Int2                           hint_node);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

