.TH ptoc 1
.SH NAME
\fBptoc\fR - PASCAL to C translator
.SH SYNOPSIS
\fBptoc\fR [\fIoptions\fR] \fIfile\fR ...
.SH DESCRIPTION
\fBPtoc\fR is a PASCAL to C translator.  All argument files ending
with \fB.p\fR, will be translated into C code, which will be written
in a file with the same basename and extension \fB.c\fR.
Argument files ending in \fB.P\fR will be processed by the C preprocessor
before being translated to C files.
.PP
The resulting C files may then be compiled with a C compiler and linked 
together with the runtime library \fB-lsqlptc\fR into an executable 
file.
.PP
The following options are recognized by \fBptoc\fR:
.PP
.TP 7
.B \-C
Compile code to produce runtime checks on array subscripts and
assignments of ordinal types other than integer.
.TP
.BI \-D name=def
.TP
.BI \-D name
Define the
.I name
to the C preprocessor, as if by `define'.
If no definition is given,
the name is defined as "1". (\fB.P\fR suffix files only.)
.TP
.B \-d
Cause the control program \fBptoc\fR to print out the invocation of
the translator \fBpgenc\fR with all it's options and arguments.
.TP
.B \-e
Enable '\\' escape character in string constants; this escape character
must be followed by a hex number, consisting of 2 hex digits, representing
the code of the escaped character.
.TP
.BI \-f xx
Fill local variables when entering a function with the byte pattern
given by the hex number \fIxx\fR consisting of 2 hex digits.
.TP
.BI \-g xx
Fill PASCAL FOR loop control variables when leaving the loop with the
byte pattern given by the hex number \fIxx\fR consisting of 2 hex digits
(the control variable will not be filled if the loop is left by a GOTO
statement).
.TP
.BI \-I dir
`#include' files whose names do not begin with `/'
are always sought first in the directory of the
.I file
argument, then in directories named in
.B \-I
options,
then in directories on a standard list.
(\fB.P\fR suffix files only.)
.TP
.B \-Kb
Break pointer types, i.e. pointers pointing to a type which is not used
in the module are declared to be pointers to integers.
.TP
.B \-Kd
Disable delayed parameter copy, i.e. when this option is not specified
value parameters of type array or set will be passed as pointers and
only in the called function/procedure a copy of them will be made.
.TP
.B \-Kt
Disable deleting of unused types, i.e. when this option is not specified
type declarations which are not referenced will not be output in the
C code.
.TP
.B \-Kv
Disable deleting of unsused variables, i.e. when this option is not specified
declarations of variables which are not referenced will not be output in the
C code.
.TP
.B \-l
Make a program listing during translation.
.TP
.BR \-O
Invoke a code optimizer.
The optimizer sometimes significantly increases
compile time and, under normal circumstances,
should only be invoked when development of the program
is complete.
The optimizer attempts to detect
all uses of and assignments to a program's variables.
Programs that communicate via shared memory or
invoke signal handlers that modify variables
accessed elsewhere in the program are candidates
for incorrect optimization.
The optimizer should be used on any program
where execution speed is important.
.TP
.B \-qn
Allocate bytes and shorts for subranges, enumerated
types and sets as appropriate.
.TP     
.B \-s
Accept standard PASCAL source only.
Non-standard constructs will cause error diagnostics.
.TP
.B \-v
Print global optimization statistics.
.TP
.BI \-W n
Issue a warning for value parameters, which have a size greater than
the decimal number \fIn\fR specified in the option.
.TP
.B \-Xa
Generate ANSI C function prototypes for PASCAL \fBforward\fR and
\fBexternal\fR functions/procedures.
.TP
.B \-Xc
Generate symbolic constants instead of literal constants for PASCAL
\fBconst\fR definitions and enumerations.
.TP
.B \-Xp
Allow pointer expressions like those in the C language (i.e. <ptr> + <int>,
<ptr> - <int> and <ptr> - <ptr>).
.TP
.B \-Xx
Generate static link structures for nested procedures in PASCAL; this option
must be used if the PASCAL program contains nested functions/procedures in 
which non-local/non-global variables are referenced.
.TP
.B \-ypc
Special options to allow PASCAL extensions from \fBPyramid Technology Corp.\fR;
this option is especially used for the \fBptoc\fR sources.

.PP
The following options are only used to produce debug output for \fBptoc\fR
and are not relevant for the \fBptoc\fR user:
.TP
.B \-W
Produce some debug output in the C source code.
.TP
.B \-XD
Print HDG node numbers in the generated C code.
.TP
.B \-XH
Print the HDG tree on standard output.
.TP
.B \-Xi
Inhibit the flushing of the debug output.
.TP
.B \-XQ
Produce debug output from the C code generator.
.TP
.B \-XT
Print the symbol table on standard output. 

.PP
For all other options \fBptoc\fR will issue a warning and ignore them.
Also for any file name that doesn't have the suffix \fB.p\fR or \fB.P\fR a warning
will be issued and the name will be ignored.
.SH FILES
.TP 22
file\&.p                   
pascal source files
.TP
/bin/ptoc          
control program
.TP
/lib/pgenc           
translator
.TP
/lib/how_pc          
basic usage explanation
.TP
/lib/libsqlptc.a         
runtime library
.SH DOCUMENTATION
.IR "Targon  Pascal" .
.PP
Nixdorf Computer AG
.br
Edition: 01.03.88, Order no. 10268.00.3.93-02
.PP
For a basic explanation, type:
.sp
.in +10
          \fBptoc\fR
.in -10
.SH LIMITATIONS
.PP
Non-local GOTO from PASCAL is not supported by \fBptoc\fR.
