#  @(#)loaderdoc.mac     
#
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

? defaultlayer : SAPDB/Scripting/Resource/loaderdoc
::SAPDB/Scripting/Resource/loaderdoc/doc/oim/oim.mac
::SAPDB/Scripting/Resource/loaderdoc/doc/cwm/cwm.mac
 :SAPDB/Scripting/Resource/loaderdoc/demo/import.py
::SAPDB/Scripting/Resource/loaderdoc/demo/sourcedb/sourcedb.mac
 :SAPDB/Scripting/Resource/loaderdoc/test/test_re.py
 :SAPDB/Scripting/Resource/loaderdoc/test/test_csv.py
 :SAPDB/Scripting/Resource/loaderdoc/test/test_loader.py
 :SAPDB/Scripting/Resource/loaderdoc/test/test_install.bat
 :SAPDB/Scripting/Resource/loaderdoc/test/transport.par
 :SAPDB/Scripting/Resource/loaderdoc/test/transport.cfg
 #performance
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_11_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_12_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_13_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_14_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_15_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_16_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_17_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_18_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_1_package.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_11_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_12_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_13_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_14_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_15_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_16_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_17_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_18_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_1_package.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_data.txt
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_package.txt
&if $OS in [ WIN32 ]
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_1_package.bat
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_1_package.bat
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_package.bat 
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_1_data.bat
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_1_data.bat
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_data.bat
&else
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_1_package
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_1_package
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_package
 :SAPDB/Scripting/Resource/loaderdoc/performance/export_1_data
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_1_data
 :SAPDB/Scripting/Resource/loaderdoc/performance/import_2_data
&endif

  