/*
        ========== licence begin  GPL
        Copyright (C) 2005 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end
 */
#ifndef RTE_HSS_MESSAGES_HPP
#define RTE_HSS_MESSAGES_HPP

// Generated Header file RTE_HSS_Messages.hpp.
// Generated by genmsg V2.2 DO NOT EDIT

#include "SAPDBCommon/ErrorsAndMessages/SAPDBErr_MessageList.hpp"

#define RTEERR_HSS_API_MESSAGE                         SAPDBErr_MessageList::Error,13900,"RTEHSS_API [%s]",1
#define RTEERR_HSS_API_MESSAGE_ID 13900
#define RTEERR_HSS_LOCAL_NODE_TOO_LONG                 SAPDBErr_MessageList::Error,13901,"Local node name '%s' too long",1
#define RTEERR_HSS_LOCAL_NODE_TOO_LONG_ID 13901
#define RTEERR_HSS_DEFAULT_MASTER_NODE_MISSING         SAPDBErr_MessageList::Error,13902,"Default master node missing",0
#define RTEERR_HSS_DEFAULT_MASTER_NODE_MISSING_ID 13902
#define RTEERR_HSS_ROLE_UNKNOWN                        SAPDBErr_MessageList::Error,13904,"Standby role not known!",0
#define RTEERR_HSS_ROLE_UNKNOWN_ID 13904
#define RTEERR_HSS_UNEXPECTED_REPLY                    SAPDBErr_MessageList::Error,13905,"Command '%s' got unexpected reply '%s'",2
#define RTEERR_HSS_UNEXPECTED_REPLY_ID 13905
#define RTEERR_HSS_MISSING_REPLY_CONTEXT               SAPDBErr_MessageList::Error,13906,"Missing reply context for command '%s' with reply '%s'",2
#define RTEERR_HSS_MISSING_REPLY_CONTEXT_ID 13906
#define RTEERR_HSS_MUST_HAVE_STANDBY_ROLE              SAPDBErr_MessageList::Error,13907,"Must have standby role set before '%s' is allowed",1
#define RTEERR_HSS_MUST_HAVE_STANDBY_ROLE_ID 13907
#define RTEERR_HSS_MUST_HAVE_MASTER_ROLE               SAPDBErr_MessageList::Error,13908,"Must have master role set before '%s' is allowed",1
#define RTEERR_HSS_MUST_HAVE_MASTER_ROLE_ID 13908
#define RTEERR_HSS_CALLING_MYSELF                      SAPDBErr_MessageList::Error,13909,"Calling own node for '%s'",1
#define RTEERR_HSS_CALLING_MYSELF_ID 13909
#define RTEERR_HSS_COMMAND_PIPE_OPEN                   SAPDBErr_MessageList::Error,13910,"Opening command pipe for '%s' failed [%s]",2
#define RTEERR_HSS_COMMAND_PIPE_OPEN_ID 13910
#define RTEERR_HSS_COMMAND_PIPE_CLOSE                  SAPDBErr_MessageList::Error,13911,"Closing command pipe for '%s' failed [%s]",2
#define RTEERR_HSS_COMMAND_PIPE_CLOSE_ID 13911
#define RTEERR_HSS_BAD_API_MESSAGE                     SAPDBErr_MessageList::Error,13912,"RTEHSS_API Type ?[%s] [%s]",2
#define RTEERR_HSS_BAD_API_MESSAGE_ID 13912
#define RTEERR_HSS_BAD_CLIENT_COMMAND_STRING           SAPDBErr_MessageList::Error,13913,"Illegal kernel to kernel command string: %s",1
#define RTEERR_HSS_BAD_CLIENT_COMMAND_STRING_ID 13913
#define RTEERR_HSS_OPEN_OUTPUT_PIPE                    SAPDBErr_MessageList::Error,13916,"Open output pipe '%s' failed [%s]",2
#define RTEERR_HSS_OPEN_OUTPUT_PIPE_ID 13916
#define RTEERR_HSS_OUTPUT_PIPE_READ                    SAPDBErr_MessageList::Error,13917,"Read output pipe failed [%s]",1
#define RTEERR_HSS_OUTPUT_PIPE_READ_ID 13917
#define RTEWARN_HSS_API_MESSAGE                        SAPDBErr_MessageList::Warning,13940,"RTEHSS_API [%s]",1
#define RTEWARN_HSS_API_MESSAGE_ID 13940
#define RTEINFO_HSS_API_MESSAGE                        SAPDBErr_MessageList::Info,13950,"RTEHSS_API [%s]",1
#define RTEINFO_HSS_API_MESSAGE_ID 13950
#define RTEINFO_HSS_NO_NODE_CONFIGURED                 SAPDBErr_MessageList::Info,13951,"No hot standby node configured -> No HotStandby configuration",0
#define RTEINFO_HSS_NO_NODE_CONFIGURED_ID 13951
#define RTEINFO_HSS_SET_ROLE_MASTER                    SAPDBErr_MessageList::Info,13952,"Standby role set: MASTER",0
#define RTEINFO_HSS_SET_ROLE_MASTER_ID 13952
#define RTEINFO_HSS_SET_ROLE_STANDBY                   SAPDBErr_MessageList::Info,13953,"Standby role set: STANDBY (master node %s)",1
#define RTEINFO_HSS_SET_ROLE_STANDBY_ID 13953
#define RTEINFO_HSS_VALID_CONFIGURATION                SAPDBErr_MessageList::Info,13954,"HSS Initialization succeeded. Own node %s delay time %s",2
#define RTEINFO_HSS_VALID_CONFIGURATION_ID 13954

#endif /* RTE_HSS_MESSAGES_HPP */
