#
# DBMCli_KernelEventing.mac
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2002-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

########################

## event dispatcher
::SAPDB/DBM/Cli/Eventing/DBMCliEvt_Dispatcher.lnk distrib

## event handler display event
::SAPDB/DBM/Cli/Eventing/DBMCliEvt_DisplayEvent.lnk distrib

&if $OS in [ WIN32 ]
## event handler write to Windows Event Log
# resource library
::SAPDB/ToolsCommon/Tools_WinEvtLog.dld distrib
# the handler itself
::SAPDB/DBM/Cli/Eventing/DBMCliEvt_WinLogger.lnk distrib
&endif