#  @(#)dbmperl.mac     7.2.0   1999-04-08
#  perl scripting interfaces to db manager
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

&if (defined BIT64) and ($MACH in [_IBMR2, SUN, PA20W])
   # build only 32 bit scripting on these platforms
&elif (defined BIT64) and ($OSSPEC = WIN32)
    # build only 32 bit perl libs on this platforms
&else

&if $OS in [ WIN32, OS2 ]
::SAPDB/Scripting/Resource/dbmap   # ActivePerl
&else
::SAPDB/Scripting/Resource/dbmcp   # core Perl
&endif

&else
! echo nothing to do...
&endif

