#  @(#)loadercp.mac     7.2.0   1999-04-08
#  core Perl loader wrapper
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

&if $COREPERL_INCLUDE <> NO
# build only if Perl includes can be found

::SAPDB/Scripting/Resource/loadercperl.dld distrib
:SAPDB/Scripting/loader.pm distrib

&ifndef XCOMP

# test module can be loaded
#&if $OS = WIN32
#! SET PERL5LIB=%INSTMISC%& perl -e "use SAP::DBTech::loader;"
#&else
#! PERL5LIB=$INSTMISC perl -e "use SAP::DBTech::loader;"
#&endif

&endif
&endif

