# scriptpython.mac
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2002-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

? defaultlayer : SAPDB/Scripting/Resource
sdb__init__.py distrib

&if $OSSPEC == WIN32 && $MACH == AMD64
pythonVariants-py23.mac
&elif $OSSPEC == WIN32 && $MACH == I386 && defined BIT64
pythonVariants-py21.mac
pythonVariants-py23.mac
&elif $OSSPEC == SOLARIS
pythonVariants-py23.mac
&else
pythonVariants-py15.mac
pythonVariants-py20.mac
pythonVariants-py21.mac
pythonVariants-py22.mac
pythonVariants-py23.mac
pythonVariants-py24.mac
pythonVariants-py25.mac
&endif

&if $OSSPEC == LINUX
pythonVariants-py22ucs4.mac
pythonVariants-py23ucs4.mac
pythonVariants-py24ucs4.mac
pythonVariants-py25ucs4.mac
&endif

:in/ireport.py distrib

# compatibility with old versions

sapdb__init__.py distrib
dbmtop.py distrib
loadertop.py distrib
sqltop.py distrib
dbapitop.py distrib

