
/*******************************************************************************

  module:       hsp42.h

  ------------------------------------------------------------------------------

  responsible:  RudolfM

  purpose:      GETSTRING-Conversions

  lastChanged:  2002-12-16

  generatedBy:  $TOOL/bin/ptocProto.py

  ------------------------------------------------------------------------------

  copyright:    Copyright (c) 1999-2005 SAP AG



    ========== licence begin  GPL
    Copyright (c) 1999-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end



********************************************************************************/

#ifndef HSP42_H
#define HSP42_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x40\xc1\x97\x90\x73\xb3\x4c\x71\x40\x9a\xa5\x74\x03\xa3\xfb\x7f'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void s42gstr (
    void                  *  buf,
    tsp00_Int4                           pos,
    integer                              len,
    integer                              frac,
    integer                              origlen,
    void                  *  dest,
    tsp00_Int4                           dpos,
    integer               VAR_VALUE_REF  dlen,
    tsp00_NumError        VAR_VALUE_REF  res);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s42gchr (
    void                  *  buf,
    tsp00_Int4                           pos,
    integer                              len,
    integer                              frac,
    integer                              origlen,
    void                  *  dest,
    tsp00_Int4                           dpos,
    integer               VAR_VALUE_REF  dlen,
    tsp00_NumError        VAR_VALUE_REF  res);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void s42gochr (
    void                  *  buf,
    tsp00_Int4                           pos,
    void                  *  dest,
    tsp00_Int4                           dpos,
    integer               VAR_VALUE_REF  dlen,
    tsp00_NumError        VAR_VALUE_REF  res);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

