# :tt/cpan/XML/Parser.mac
#
#    ========== licence begin LGPL
#    Copyright (C) 2002 SAP AG
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    ========== licence end
#

:tt/cpan/XML/Parser/Changes
:tt/cpan/XML/Parser/README
:tt/cpan/XML/Parser/MANIFEST
:tt/cpan/XML/Parser/Makefile.PL
:tt/cpan/XML/Parser/Parser.pm

:tt/cpan/XML/Parser/t/astress.t
:tt/cpan/XML/Parser/t/cdata.t
:tt/cpan/XML/Parser/t/decl.t
:tt/cpan/XML/Parser/t/defaulted.t
:tt/cpan/XML/Parser/t/encoding.t
:tt/cpan/XML/Parser/t/ext2.ent
:tt/cpan/XML/Parser/t/ext.ent
:tt/cpan/XML/Parser/t/external_ent.t
:tt/cpan/XML/Parser/t/file.t
:tt/cpan/XML/Parser/t/finish.t
:tt/cpan/XML/Parser/t/namespaces.t
:tt/cpan/XML/Parser/t/parament.t
:tt/cpan/XML/Parser/t/partial.t
:tt/cpan/XML/Parser/t/skip.t
:tt/cpan/XML/Parser/t/stream.t
:tt/cpan/XML/Parser/t/foo.dtd

:tt/cpan/XML/Parser/Parser/LWPExternEnt.pl

:tt/cpan/XML/Parser/Parser/Encodings/README
:tt/cpan/XML/Parser/Parser/Encodings/big5.enc
:tt/cpan/XML/Parser/Parser/Encodings/euc_kr.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_2.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_3.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_4.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_5.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_7.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_8.enc
:tt/cpan/XML/Parser/Parser/Encodings/iso_8859_9.enc
:tt/cpan/XML/Parser/Parser/Encodings/Japanese_Encodings.msg
:tt/cpan/XML/Parser/Parser/Encodings/windows_1250.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_euc_jp_jisx0221.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_euc_jp_unicode.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_sjis_cp932.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_sjis_jdk117.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_sjis_jisx0221.enc
:tt/cpan/XML/Parser/Parser/Encodings/x_sjis_unicode.enc

:tt/cpan/XML/Parser/samples/canonical
:tt/cpan/XML/Parser/samples/canontst.xml
:tt/cpan/XML/Parser/samples/ctest.dtd
:tt/cpan/XML/Parser/samples/REC_xml_19980210.xml
:tt/cpan/XML/Parser/samples/xmlcomments
:tt/cpan/XML/Parser/samples/xmlfilter
:tt/cpan/XML/Parser/samples/xmlstats

:tt/cpan/XML/Parser/Expat/encoding.h
:tt/cpan/XML/Parser/Expat/expat.patches
:tt/cpan/XML/Parser/Expat/Expat.pm
:tt/cpan/XML/Parser/Expat/Expat.xs
:tt/cpan/XML/Parser/Expat/Makefile.PL
:tt/cpan/XML/Parser/Expat/pm_to_blib
:tt/cpan/XML/Parser/Expat/README
:tt/cpan/XML/Parser/Expat/typemap

:tt/cpan/XML/Parser/Expat/expat/expat.html
:tt/cpan/XML/Parser/Expat/expat/xmlparse/hashtable.c
:tt/cpan/XML/Parser/Expat/expat/xmlparse/hashtable.h
:tt/cpan/XML/Parser/Expat/expat/xmlparse/xmlparse.h
:tt/cpan/XML/Parser/Expat/expat/xmlparse/xmlparse.c

:tt/cpan/XML/Parser/Expat/expat/xmltok/ascii.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/asciitab.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/iasciitab.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/latin1tab.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/nametab.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/utf8tab.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmldef.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmlrole.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmlrole.c
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmltok.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmltok.c
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmltok_impl.h
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmltok_impl.c
:tt/cpan/XML/Parser/Expat/expat/xmltok/xmltok_ns.c


&if $OS = UNIX
!cd $TOOL/src/cpan/XML-Parser; $TOOLSHELL Makefile.PL PREFIX=$TOOL/lib/perl5; gmake; gmake test; make install
&else
!cd %TOOL%\src\cpan\XML-Parser && %TOOLSHELL% Makefile.PL PREFIX=%TOOL%\lib\perl5 && nmake && nmake install 
&endif

