*
*  Responsible: JoergM
*
*  File needed for AIX only, to export kernel symbols
*
*  At start, only the global C++ new/delete operators were exported...
*
*  NOTE C++ symbols must be given in their compiler specific mangled strings
*
*  copyright:    Copyright (c) 2000-2004 SAP AG
*
*
*   ========== licence begin  GPL
*   Copyright (c) 2000-2004 SAP AG
*
*   This program is free software; you can redistribute it and/or
*   modify it under the terms of the GNU General Public License
*   as published by the Free Software Foundation; either version 2
*   of the License, or (at your option) any later version.
*
*   This program is distributed in the hope that it will be useful,
*   but WITHOUT ANY WARRANTY; without even the implied warranty of
*   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*   GNU General Public License for more details.
*
*   You should have received a copy of the GNU General Public License
*   along with this program; if not, write to the Free Software
*   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
*    ========== licence end
*
__nw__FUl
__dl__FPv
__vn__FUl
__vd__FPv
*
* this is a work arounds...  (problems with calls used in UNIX runtime not completely using RTE_IInterface)...
*
sql60c_msg_8
