# DBD.mac
#    ========== licence begin  GPL
#    Copyright (c) 2001-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

? propagate : SQLDBCSDK=$INSTROOT

&if defined SERVERDB 
&if defined SERVERNODE
? propagate : DBI_DSN=dbi:MaxDB:$SERVERNODE/$SERVERDB
&else
? propagate : DBI_DSN=dbi:MaxDB:$SERVERDB
&endif
&endif

&if defined SUPERUID 
? propagate : DBI_USER=$SUPERUID
&endif

&if defined SUPERPWD 
? propagate : DBI_PASS=$SUPERPWD
&endif

::SAPDB/Interfaces/SQLDBC/SQLDBC.mac

:SAPDB/Interfaces/Perl/DBD/MANIFEST
:SAPDB/Interfaces/Perl/DBD/MANIFEST.SKIP
:SAPDB/Interfaces/Perl/DBD/Makefile.PL
:SAPDB/Interfaces/Perl/DBD/MaxDB.pm setbuildinfo dep=:config/Buildinfo/VERSIONS
:SAPDB/Interfaces/Perl/DBD/MaxDB.xs
:SAPDB/Interfaces/Perl/DBD/README.pod setbuildinfo dep=:config/Buildinfo/VERSIONS
:SAPDB/Interfaces/Perl/DBD/GetInfo.pm
:SAPDB/Interfaces/Perl/DBD/TypeInfoAscii.pm
:SAPDB/Interfaces/Perl/DBD/TypeInfoUnicode.pm
:SAPDB/Interfaces/Perl/DBD/dbdimp.c
:SAPDB/Interfaces/Perl/DBD/dbdimp.h
:SAPDB/Interfaces/Perl/DBD/t/050connect.t
:SAPDB/Interfaces/Perl/DBD/t/051properties.t
:SAPDB/Interfaces/Perl/DBD/t/052ping.t
:SAPDB/Interfaces/Perl/DBD/t/053do.t
:SAPDB/Interfaces/Perl/DBD/t/054fetch.t
:SAPDB/Interfaces/Perl/DBD/t/055bindcolumns.t
:SAPDB/Interfaces/Perl/DBD/t/056stmtproperties.t
:SAPDB/Interfaces/Perl/DBD/t/057stmtstdproperties.t
:SAPDB/Interfaces/Perl/DBD/t/058blobread.t
:SAPDB/Interfaces/Perl/DBD/t/059tableinfo.t
:SAPDB/Interfaces/Perl/DBD/t/060tableinfo2.t
:SAPDB/Interfaces/Perl/DBD/t/061columninfo.t
:SAPDB/Interfaces/Perl/DBD/t/063trailingzerobytes.t
:SAPDB/Interfaces/Perl/DBD/t/064defaultvalues.t
:SAPDB/Interfaces/Perl/DBD/t/065nestedselect.t
:SAPDB/Interfaces/Perl/DBD/t/001base.t
:SAPDB/Interfaces/Perl/DBD/t/002simple.t
:SAPDB/Interfaces/Perl/DBD/t/100connectproperties.t
:SAPDB/Interfaces/Perl/DBD/t/101connect_cached.t
:SAPDB/Interfaces/Perl/DBD/t/102driverdatasource.t
:SAPDB/Interfaces/Perl/DBD/t/103trace.t
:SAPDB/Interfaces/Perl/DBD/t/104do_insert_update_delete.t
:SAPDB/Interfaces/Perl/DBD/t/105selectrow_array.t
:SAPDB/Interfaces/Perl/DBD/t/106selectall_arrayref.t
:SAPDB/Interfaces/Perl/DBD/t/107selectall_arrayref_big.t
:SAPDB/Interfaces/Perl/DBD/t/108selectcol_arrayref.t
:SAPDB/Interfaces/Perl/DBD/t/109selectcol_arrayref_big.t
:SAPDB/Interfaces/Perl/DBD/t/110prepare_cached.t
#:SAPDB/Interfaces/Perl/DBD/t/111err_errstr_state.t
:SAPDB/Interfaces/Perl/DBD/t/112experimental.t
:SAPDB/Interfaces/Perl/DBD/t/113prepare.t
:SAPDB/Interfaces/Perl/DBD/t/114disconnect.t
:SAPDB/Interfaces/Perl/DBD/t/115quote.t
:SAPDB/Interfaces/Perl/DBD/t/116bind_param.t
:SAPDB/Interfaces/Perl/DBD/t/117execute.t
:SAPDB/Interfaces/Perl/DBD/t/118emptyresultset.t
:SAPDB/Interfaces/Perl/DBD/t/119bind_param_inout.t
:SAPDB/Interfaces/Perl/DBD/t/120fetchrow_array.t
:SAPDB/Interfaces/Perl/DBD/t/121fetchrow_arrayref.t
:SAPDB/Interfaces/Perl/DBD/t/122fetchrow_hashref.t
:SAPDB/Interfaces/Perl/DBD/t/123fetchall_arrayref.t
:SAPDB/Interfaces/Perl/DBD/t/130bind_col.t
:SAPDB/Interfaces/Perl/DBD/t/131bind_columns.t
:SAPDB/Interfaces/Perl/DBD/t/133blobfetch.t
:SAPDB/Interfaces/Perl/DBD/t/134unicode.t
:SAPDB/Interfaces/Perl/DBD/t/135ChopBlanks.t
:SAPDB/Interfaces/Perl/DBD/t/136AutoCommit.t
:SAPDB/Interfaces/Perl/DBD/t/137stmtstdproperties2.t
:SAPDB/Interfaces/Perl/DBD/t/138severalstmts.t
:SAPDB/Interfaces/Perl/DBD/t/139fetchAllTypes.t
:SAPDB/Interfaces/Perl/DBD/t/142UndefParameter.t
:SAPDB/Interfaces/Perl/DBD/t/143BooleanTypeHandling.t
:SAPDB/Interfaces/Perl/DBD/t/144simpleunicode.t
:SAPDB/Interfaces/Perl/DBD/t/145simple8bitascii.t
:SAPDB/Interfaces/Perl/DBD/t/MaxDBTest.pm
:SAPDB/Interfaces/Perl/DBD/t/mysql_00base.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_10dsnlist.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_20createdrop.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_30insertfetch.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_40bindparam.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_40listfields.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_40nulls.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_40numrows.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_50chopblanks.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_50commit.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_akdbd.t
:SAPDB/Interfaces/Perl/DBD/t/mysql_dbdadmin.t
:SAPDB/Interfaces/Perl/DBD/t/lib.pl
:SAPDB/Interfaces/Perl/DBD/t/MaxDB.dbtest
:SAPDB/Interfaces/Perl/DBD/t/MaxDB.mtest
&if $OS = UNIX
#!cd $OWN/usr/misc/DBD-MaxDB ; touch Makefile.PL ; $TOOLSHELL Makefile.PL
&endif

&if $OSSPEC = WIN32
!!(if not exist %WRK%\fast\install mkdir %WRK%\fast\install)

&if defined DBDPERL
!!+cd %WRK%\obj\SAPDB\Interfaces\Perl\DBD && %DBDPERL% Makefile.PL && nmake dist
&else
!!+cd %WRK%\obj\SAPDB\Interfaces\Perl\DBD && %TOOLSHELL% Makefile.PL && nmake dist
&endif

&else

!!mkdir -p $WRK/fast/install
!!+cd $WRK/obj/SAPDB/Interfaces/Perl/DBD && $TOOLSHELL Makefile.PL && make dist

&endif


perlpkgcopy binary <-$WRK/obj/SAPDB/Interfaces/Perl/DBD/DBD-MaxDB-7.6.00.$BUILDPRAEFIX.tar.gz \
            ->$WRK/fast/install/DBD-MaxDB-7_6_00_$BUILDPRAEFIX.tar.gz \
            nocomfile distrib



