# -----------------------------------------------------------------------------
# module:    SQLDBC.mac
#
# responsible: DL_SAP_DB_INTERFACES
#
# special area: Makes the all of SAP Database Connectivity
# description:
#
# see:
#
# change history:
# -----------------------------------------------------------------------------
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

libSQLDBC.dld distrib
libSQLDBC76.dld uncond distrib
libSQLDBCs.lib distrib
libSQLDBC_C.dld distrib
SQLDBC-sdk.h distrib
SQLDBC-sqldbc_c.h distrib
SQLDBC_Types-sdk.h distrib
&if $OS = WIN32
sqldbcsdklib binary <-$INSTLIB/libSQLDBC.lib ->$INSTROOT/sdk/sqldbc/lib/libSQLDBC.lib nocomfile distrib
sqldbccsdklib binary <-$INSTLIB/libSQLDBC_C.lib ->$INSTROOT/sdk/sqldbc/lib/libSQLDBC_C.lib nocomfile distrib
# Generate release dependent libraries
sqldbc76dll binary <-$INSTROOT/pgm/libSQLDBC76.dll ->$INSTROOT/pgm/libSQLDBC76.dll nocomfile distrib
sqldbc76lib binary <-$INSTLIB/libSQLDBC76.lib ->$INSTROOT/sdk/sqldbc/lib/libSQLDBC76.lib nocomfile distrib
&else
sqldbcsdklib binary <-$INSTLIB/libSQLDBC.a ->$INSTROOT/sdk/sqldbc/lib/libSQLDBC.a nocomfile distrib
sqldbccsdklib binary <-$INSTLIB/libSQLDBC_C.a ->$INSTROOT/sdk/sqldbc/lib/libSQLDBC_C.a nocomfile distrib
&endif
SQLDBC_Catalog.cpp
