/*!******************************************************************************

  @file         hkb50_2.h

  ------------------------------------------------------------------------------

  @author       UweH

  @brief        KB_trans_state

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HKB50_2_H
#define HKB50_2_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xd2\x5b\x25\xa5\xad\x99\x00\x5b\x0f\xdd\x43\x5d\xc3\x41\x2a\xd7'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void k50hash (
    void                  *  buf,
    tsp00_Int4               pos,
    tsp00_Int4               len,
    void                  *  ResBuf,
    integer                  ResPos);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

