/*!******************************************************************************

  @file         hkb571.h

  ------------------------------------------------------------------------------

  @author       UweH

  @brief        KB_RefreshSurrogSeq_interface

\if EMIT_LICENCE  

    ========== licence begin  GPL
    Copyright (c) 2001-2005 SAP AG

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end

\endif

********************************************************************************/

#ifndef HKB571_H
#define HKB571_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x88\xe5\xb3\xa4\x4b\xa8\x28\xf1\x2e\x74\xa6\xa1\x35\xa5\x0a\xb1'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void kb571GetOldestCompatibleVersionString (
    tsp00_C10             VAR_ARRAY_REF  version);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb571WriteRefreshSeqAfterImage (
    tgg00_TransContext    VAR_VALUE_REF  TransContext,
    tsp00_Int4                           SequenceCount,
    const tsp00_Addr                     pSequenceList);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb571WriteRefreshSurrogAfterImage (
    tgg00_TransContext    VAR_VALUE_REF  TransContext,
    const tgg00_Surrogate  VAR_ARRAY_REF  Surrogate,
    const tgg00_Surrogate  VAR_ARRAY_REF  SysKey);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb571InitializeWaitList ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb571AllSurrogateWaitsResume ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb571SurrogateWaitInsert (
    tsp00_TaskId                         taskid,
    tgg00_WaitContext     VAR_VALUE_REF  waitcontext);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

