/*
        ========== licence begin  GPL
        Copyright (C) 2005 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end
 */
#ifndef SAPDBFIELDS_MESSAGES_HPP
#define SAPDBFIELDS_MESSAGES_HPP

// Generated Header file SAPDBFields_Messages.hpp.
// Generated by genmsg V2.2 DO NOT EDIT

#include "SAPDBCommon/ErrorsAndMessages/SAPDBErr_MessageList.hpp"

#define FIELDS_OFFSET_OUT_OF_RANGE            SAPDBErr_MessageList::Error,20000,"Offset %s greater then Length %s",2
#define FIELDS_OFFSET_OUT_OF_RANGE_ID 20000
#define FIELDS_OFFSET_AND_LENGTH_OUT_OF_RANGE SAPDBErr_MessageList::Error,20001,"Offset %s and Length %s are greater then Length %s",3
#define FIELDS_OFFSET_AND_LENGTH_OUT_OF_RANGE_ID 20001
#define FIELD_INVALID_FIELDNO                 SAPDBErr_MessageList::Error,20002,"requested fieldno %s must be smaller then %s",2
#define FIELD_INVALID_FIELDNO_ID 20002
#define FIELDLIST_NOT_IMPLEMENTED             SAPDBErr_MessageList::Error,20003,"The class SAPDBFields_FieldList is not implemented.",0
#define FIELDLIST_NOT_IMPLEMENTED_ID 20003
#define FIELD_ATTRIBUTE_INVALID               SAPDBErr_MessageList::Error,20004,"Invalid FieldValues: Attribute=%s Length=%s",2
#define FIELD_ATTRIBUTE_INVALID_ID 20004
#define LENGTHFIELD_TOO_SMALL                 SAPDBErr_MessageList::Error,20005,"The given length %s is smaller then required %s",2
#define LENGTHFIELD_TOO_SMALL_ID 20005
#define LENGTHFIELD_NOT_ASSIGNED              SAPDBErr_MessageList::Error,20006,"Used Field of LengthField used by FieldList is not assigned.",0
#define LENGTHFIELD_NOT_ASSIGNED_ID 20006
#define LENGTHFIELD_INVALID_ATTRIBUTE         SAPDBErr_MessageList::Error,20007,"Attribute %s is invalid in this context.",1
#define LENGTHFIELD_INVALID_ATTRIBUTE_ID 20007
#define FIELDLIST_TEST_FAILED                 SAPDBErr_MessageList::Error,20008,"FieldList.Test Error: %s",1
#define FIELDLIST_TEST_FAILED_ID 20008
#define FIELDLIST_TEST_FAILED2                SAPDBErr_MessageList::Error,20009,"FieldList.Test Error: %s value=%s",2
#define FIELDLIST_TEST_FAILED2_ID 20009
#define FIELDLIST_IS_NOT_ASSIGNED             SAPDBErr_MessageList::Error,20010,"The fieldlist is not assigned.",0
#define FIELDLIST_IS_NOT_ASSIGNED_ID 20010
#define FIELDLIST_IS_CORRUPTED                SAPDBErr_MessageList::Error,20011,"Corrupted Fieldlist: GetField failed curr=%s currOff=%s LengthLen=%s Length=%s",4
#define FIELDLIST_IS_CORRUPTED_ID 20011
#define FIELDLIST_HANDLE_IS_CORRUPT           SAPDBErr_MessageList::Error,20012,"Corrupted FieldListHandle: end of list reached but fieldno %s of %s not found",2
#define FIELDLIST_HANDLE_IS_CORRUPT_ID 20012
#define FIELD_CONTEXT_INFO                    SAPDBErr_MessageList::Info,20013,"%s: length=%s ptr=%s",3
#define FIELD_CONTEXT_INFO_ID 20013
#define FIELDATTRIBUTED_CONTEXT_INFO          SAPDBErr_MessageList::Info,20014,"Field is attributed with %s",1
#define FIELDATTRIBUTED_CONTEXT_INFO_ID 20014
#define FIELDLIST_CONTEXT_INFO                SAPDBErr_MessageList::Info,20015,"%s: fieldcount=%s firstfreeoffset=%s",3
#define FIELDLIST_CONTEXT_INFO_ID 20015

#endif /* SAPDBFIELDS_MESSAGES_HPP */
