/*!******************************************************************************

  @file         hkb05.h

  ------------------------------------------------------------------------------

  @author       UweH

  @brief        KB_functions

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HKB05_H
#define HKB05_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x05\x42\x98\x5c\x4b\x55\x96\x57\x85\x02\xa4\x6c\x88\x3d\xb0\x04'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void k05cold_functions (
    tgg00_MessBlock       &  mblock);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void k05functions (
    tgg00_MessBlock       &  mblock);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void k05GetBadLogVolume (
    tgg00_MessBlock       &  mblock);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void k05init ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool k05is_fatal_error (
    tgg00_BasisError         e);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tsp00_Int4 k05MaxStackUsage ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb05ReturnErrorHandling (
    tgg00_TransContext    &  Trans,
    pasbool                  BeginSubtransSet,
    tgg00_MessType_Param     StartMessType);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

