/*!******************************************************************************

  @file         hkb661.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2001-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HKB661_H
#define HKB661_H


/*===========================================================================*
 *     RefType: Both                                                         *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\x21\xde\xfe\x74\x67\xcd\x12\xe6\x70\x34\x2a\x32\x30\xea\xb8\xe2'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal void kb661ModifyTable (
    tgg00_TransContext    VAR_VALUE_REF  TransContext,
    tgg00_FileId          VAR_VALUE_REF  SourceFileId,
    tgg00_FileId          VAR_VALUE_REF  IndexFileId,
    tgg00_FileId          VAR_VALUE_REF  DestinFileId,
    tsp00_Int4                           StackListEntries,
    const tgg00_StackListPtr                 SourceStackList,
    const tgg00_StackListPtr                 DestinStackList,
    pasbool                              IsSorted,
    tsp00_Int4                           TruncCheckPos,
    tsp00_Int4                           TruncCheckCnt,
    tgg00_SampleInfo      VAR_VALUE_REF  ResultSampleInfo);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb661ReassignSecondaryFile (
    tgg00_TransContext    VAR_VALUE_REF  transContext,
    tgg00_Surrogate       VAR_ARRAY_REF  secondaryFileSurrogate,
    tgg00_Surrogate       VAR_ARRAY_REF  fromPrimaryFileSurrogate,
    tgg00_Surrogate       VAR_ARRAY_REF  toPrimaryFileSurrogate);

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal void kb661SetFileAttributePagesClustered (
    tgg00_TransContext    VAR_VALUE_REF  transContext,
    const tgg00_Surrogate  VAR_ARRAY_REF  fileSurrogate,
    pasbool                              bPagesClustered);

/* Don't edit this file by hand, it is generated by ptocProto.py */


#endif

