/*!******************************************************************************

  @file         hgg01_3.h

  ------------------------------------------------------------------------------

  @author       <unknown>

  @brief        <unknown topic>

\if EMIT_LICENCE

    ========== licence begin  GPL
    Copyright (c) 2000-2005 SAP AG
 
    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.
 
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
 
    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    ========== licence end
\endif

********************************************************************************/

#ifndef HGG01_3_H
#define HGG01_3_H


/*===========================================================================*
 *     RefType: C++                                                          *
 *===========================================================================*/

/*===========================================================================*
 *     MD5: '\xc8\xa9\x07\xb7\x55\x10\x55\xec\xa3\x3d\x2c\xd4\xa4\x47\x41\x67'
 *===========================================================================*/


/*===========================================================================*
 *  INCLUDES                                                                 *
 *===========================================================================*/

#include "gsp00.h"
#include "ggg00.h"
#include "ggg04.h"


/*===========================================================================*
 *  FUNCTION PROTOTYPES                                                      *
 *===========================================================================*/

externPascal pasbool g01SystemTriggersEnabled ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01UseSelectFetch ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal pasbool g01UseVariableInput ();

/* Don't edit this file by hand, it is generated by ptocProto.py */

externPascal tgg04_CodeGlobals g01code;
externPascal tgg04_ControlUser g01controluser;
externPascal pasbool g01ConsistentReadEnabled;
externPascal pasbool g01default_lru;
externPascal tgg00_KernelGlobals g01glob;
externPascal tgg00_HashPrimeList g01hashprime;
externPascal pasbool g01log_backup_to_pipe;
externPascal tsp00_Int4 g01autosave_distance;
externPascal tgg00_LongQual g01nil_long_qual;
externPascal tgg00_SfpInitPart g01nil_sel;
externPascal tgg00_StackDesc g01nil_stack_desc;
externPascal pasbool g01nls_sort;
externPascal tsp00_KnlIdentifier g01nls_default_map;
externPascal tgg04_ServerdbIdent g01serverdb_ident;
externPascal pasbool g01sysaccount;
externPascal pasbool g01diag_moni_parse_on;
externPascal tgg04_TabIdGlobals g01tabid;
externPascal tgg00_TimeoutGlobals g01timeout;
externPascal pasbool g01unicode;
externPascal tgg00_VtraceState g01vtrace;
externPascal tsp00_Int4 g01updstatalgo;
externPascal tsp00_Int4 gg01_no_of_backup_devs;
externPascal tsp00_Int4 gg01_maxcpu;
externPascal tsp00_Int4 gg01_usedmaxlogqueuecount;
externPascal tsp00_Int4 gg01_logqueuecount;
externPascal tsp00_Int4 gg01_maxlocks;
externPascal tsp00_Int4 gg01_maxtrans;
externPascal tsp00_Int4 gg01_maxuser;
externPascal tsp00_Int4 gg01_maxuserstack;
externPascal tsp00_Int4 gg01_ccp_catalog_cache_pages;
externPascal tsp00_Int4 gg01_sequence_cache_pages;
externPascal tsp00_Int4 gg01_join_prefetch_percent;
externPascal tsp00_Int4 gg01_max_merge;
externPascal tsp00_Int4 gg01_trans_regions;
externPascal tsp00_Int4 gg01_tab_regions;
externPascal tsp00_Int4 gg01_row_regions;
externPascal tsp00_Int4 gg01_oms_regions;
externPascal tsp00_Int4 gg01_data_regions;
externPascal tsp00_Int4 gg01_backup_block_count;
externPascal tsp00_Int4 gg01_maxdatawriter;
externPascal tsp00_Int4 gg01_packet_size;
externPascal tsp00_Int4 gg01_mb_data_size;
externPascal tsp00_Int4 gg01_mb_qual_size;
externPascal tsp00_Int4 gg01_mb_strat_size;
externPascal tsp00_Int4 gg01_mb_stack_size;
externPascal tsp00_Int4 gg01_kb_work_st_size;
externPascal tsp00_Int4 gg01_kb_workbuf_size;
externPascal tsp00_Int4 gg01_ccs_catalog_cache_size;
externPascal tsp00_Int4 gg01_lock_supply_block;
externPascal tsp00_Int4 gg01_deadlock_detection;
externPascal tsp00_Int4 gg01_dw_io_area_size;
externPascal tsp00_Int4 gg01_dw_io_area_flush;
externPascal tsp00_Int4 gg01_dw_lru_tail_flush;
externPascal tsp00_Int4 gg01_delay_lw;
externPascal pasbool gg01_optim_cache;
externPascal pasbool gg01_optim_inv_only;
externPascal pasbool gg01_operator_join;
externPascal pasbool gg01_operator_join_costfunc;
externPascal pasbool gg01_hashed_resultset;
externPascal pasbool gg01_clustered_lobs;
externPascal tsp00_Int4 gg01_maxgarbage_collector;
externPascal tsp00_Int4 gg01_readahead_blobs_gt;
externPascal tsp00_Int4 gg01_join_search_level;
externPascal tsp00_Int2 gg01_join_maxtab_level4;
externPascal tsp00_Int2 gg01_join_maxtab_level9;
externPascal tsp00_Int4 gg01_oms_heap_limit;
externPascal tsp00_Int4 gg01_converter_regions;
externPascal tsp00_Int4 gg01_max_ukt;
externPascal tsp00_Int4 gg01_oms_heap_usage_threshold;
externPascal tsp00_Int4 gg01_oms_vers_free_threshold;
externPascal tsp00_Int4 gg01_oms_heap_count;
externPascal tsp00_Int4 gg01_oms_heap_blocksize;
externPascal tsp00_Int4 gg01_oms_stream_timeout;
externPascal tsp00_Int4 gg01_join_tablebuffer;
externPascal tsp00_Int4 g01restart_time;
externPascal tsp00_Int4 gg01_max_retention_time;
externPascal tsp00_Int4 gg01_min_retention_time;
externPascal pasbool gg01_operator_join_sort;
externPascal tsp00_Int4 gg01_trans_threshold_value;
externPascal tsp00_Int4 gg01_trans_history_size;
externPascal pasbool gg01_enable_system_triggers;
externPascal pasbool gg01_useselectfetch;
externPascal pasbool gg01_usevariableinput;
externPascal pasbool gg01_columncompression;
externPascal pasbool gg01_checktablewidth;
externPascal pasbool gg01_kb_stack_measurement;
externPascal pasbool gg01_diag_reverse_fetch;
externPascal pasbool gg01_trigger;
externPascal pasbool gg01_one_join_phase;
externPascal pasbool gg01_aggr_optim;
externPascal pasbool gg01_diag_minmax_optim;
externPascal pasbool gg01_outer_join_ordered;
externPascal pasbool gg01_use_join_hashtable;
externPascal tsp00_Int4 gg01_sm_reads;
externPascal tsp00_Int4 gg01_sm_milliseconds;
externPascal tsp00_Int4 gg01_sm_selectivity;
externPascal tsp00_Int4 gg01_join_hash_min_ratio;
externPascal tsp00_Int4 gg01_join_parall_minsize;
externPascal tsp00_Int4 gg01optimize_parallel_server;
externPascal pasbool gg01DataCacheMemoryProtection;
externPascal pasbool gg01_optim_first_rows;
externPascal pasbool gg01_qual_on_index;

#endif

