# -----------------------------------------------------------------------------
# module:    default.mac
#
# responsible: D019882
#
# special area: Makes all of the Fastloader Testsuite
# description:
#
# see:
#
# change history:
# -----------------------------------------------------------------------------
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

::SAPDB/Loader/FastloaderTests/SimpleFLCommand.lnk
::SAPDB/Loader/FastloaderTests/MultiInitialize.lnk
::SAPDB/Loader/FastloaderTests/SimpleGetVersion.lnk
#::SAPDB/Loader/FastloaderTests/StmtExecute.lnk
#::SAPDB/Loader/FastloaderTests/StmtExecuteU.lnk
#::SAPDB/Loader/FastloaderTests/FailedStmt.lnk
#::SAPDB/Loader/FastloaderTests/FailedPreparedStmt.lnk
#::SAPDB/Loader/FastloaderTests/InsStmtExe.lnk
#::SAPDB/Loader/FastloaderTests/QueryStmt.lnk
#::SAPDB/Loader/FastloaderTests/Resultset.lnk
#::SAPDB/Loader/FastloaderTests/lobtypestest.lnk
#::SAPDB/Loader/FastloaderTests/SimpleNavigation.lnk
#::SAPDB/Loader/FastloaderTests/MassNavigation.lnk
#::SAPDB/Loader/FastloaderTests/FetchTypes.lnk
#::SAPDB/Loader/FastloaderTests/FailedFetchTypes.lnk
#::SAPDB/Loader/FastloaderTests/FetchPrevious.lnk
#::SAPDB/Loader/FastloaderTests/mttest.lnk
#::SAPDB/Loader/FastloaderTests/illegalparam.lnk
#::SAPDB/Loader/FastloaderTests/applparamtest.lnk
#::SAPDB/Loader/FastloaderTests/invdata.lnk
#::SAPDB/Loader/FastloaderTests/Blobtst001.lnk
#::SAPDB/Loader/FastloaderTests/getobject.lnk
#::SAPDB/Loader/FastloaderTests/dataexecute.lnk
#::SAPDB/Loader/FastloaderTests/NullVal.lnk
#::SAPDB/Loader/FastloaderTests/pspytest.lnk
#::SAPDB/Loader/FastloaderTests/getrow.lnk
#::SAPDB/Loader/FastloaderTests/RowSetPos.lnk
#::SAPDB/Loader/FastloaderTests/applshared.lnk
#::SAPDB/Loader/FastloaderTests/updinsert.lnk
#::SAPDB/Loader/FastloaderTests/upddelete.lnk
#::SAPDB/Loader/FastloaderTests/updupdate.lnk
#::SAPDB/Loader/FastloaderTests/testclink.mac
