/*
        ========== licence begin  GPL
        Copyright (C) 2005 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end
 */
#ifndef SAPDBERR_MESSAGES_HPP
#define SAPDBERR_MESSAGES_HPP

// Generated Header file SAPDBErr_Messages.hpp.
// Generated by genmsg V2.2 DO NOT EDIT

#include "SAPDBCommon/ErrorsAndMessages/SAPDBErr_MessageList.hpp"

#define SAPDBERR_ASSERT_STATE_FAILED    SAPDBErr_MessageList::Error,20000,"Assertion of state %s failed!",1
#define SAPDBERR_ASSERT_STATE_FAILED_ID 20000
#define SAPDBERR_ASSERT_ARGUMENT_FAILED SAPDBErr_MessageList::Error,20001,"Assertion of argument %s failed!",1
#define SAPDBERR_ASSERT_ARGUMENT_FAILED_ID 20001
#define SAPDBERR_ASSERT_RANGE_FAILED    SAPDBErr_MessageList::Error,20002,"Assertion failed: Index %s (%s) out of range [%s, %s]!",4
#define SAPDBERR_ASSERT_RANGE_FAILED_ID 20002

#endif /* SAPDBERR_MESSAGES_HPP */
