# webagent.mac
# Holger Bischoff	21.01.1999
# Markus Özgen		23.03.2000
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

gsp100.h

# WebAgent Resources
waresources.mac

# WebAgent include files
hwd01wadef.h
hwd02waapi.h
hwd03waapi.h
hwd04wases.h
hwd05wases.h
hwd06waerr.h

# WebAgent installation script
instweb.0w

# WegAgent sample ini file
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=0&ErrorID=1121205
&if $OS = WIN32

:wd/wa.reg.0w	uncond distrib
!!sed "s#\$WEBINSTROOT\$#%INSTROOT:\=\\\\%#g" %OWN%\usr\config\WA.reg > %OWN%\usr\config\WA.reg.own
!!sed "s#\$LOG\$#%INSTROOT:\=\\\\%\\\\log#g" %OWN%\usr\config\WA.reg.own > %OWN%\usr\config\WA.reg.ready
!!rm %INSTROOT%\config\WA.reg.own

&else

:wd/WebAgent76.ini.0w	uncond distrib

#&if $MACH in [ PA11 , PA20W ]
#!!sed s#\\.so#\\.sl#g $OWN/usr/config/WebAgent76.ini > $OWN/usr/config/WebAgent76.ini.tmp
#!!cp $OWN/usr/config/WebAgent76.ini.tmp $OWN/usr/config/WebAgent76.ini
#!!rm $OWN/usr/config/WebAgent76.ini.tmp
#&endif

#&if defined BIT64

#&if $OSSPEC in [OSF1, LINUX]
#!!sed s#/lib64/#/#g $OWN/usr/config/WebAgent76.ini > $OWN/usr/config/WebAgent76.ini.tmp
#!!cp $OWN/usr/config/WebAgent76.ini.tmp $OWN/usr/config/WebAgent76.ini
#!!rm $OWN/usr/config/WebAgent76.ini.tmp
#&endif

#&endif

# Make ready file
!!sed s#\$OWN32\$/#`echo $OWN`/usr/#g $OWN/usr/config/WebAgent76.ini > $OWN/usr/config/WebAgent76.ini.ready_tmp
!!sed s#\$OWN64\$/#`echo $OWN`/usr/#g $OWN/usr/config/WebAgent76.ini.ready_tmp > $OWN/usr/config/WebAgent76.ini.ready_tmp2
!!sed s#\\\$LOG\\\$#`echo $OWN`/usr/log#g $OWN/usr/config/WebAgent76.ini.ready_tmp2 > $OWN/usr/config/WebAgent76.ini.ready
!!rm $OWN/usr/config/WebAgent76.ini.ready_tmp
!!rm $OWN/usr/config/WebAgent76.ini.ready_tmp2

&endif

mime.types.0w		distrib

# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1120918
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1118259

&if $OS = WIN32
vwd95wacom.idl
&endif

############################
#
# waecho
#
############################
waecho.dld			distrib

############################
#
# websql
#
############################
websql.dld			distrib

############################
#
# Web DBM
#
############################
webdbm.dld			ff distrib

############################
#
# WebDAV
#
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1118792
#
############################
webdav.mac	        ff distrib

############################
#
# LEGACY
# ||||||
# VVVVVV
############################

# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1118725
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1119414
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1118725
# http://pts:1080/webpts?wptsdetail=yes&ErrorType=1&ErrorID=1118725

# Database-Filesystem
#wadbfs.mac

# WebAgent for CGI
#wacgi.lnk			distrib

# WebAgent FastCGI
# FastCGI has been disabled PTS: http://pts:1080/webpts?wptsdetail=yes&ErrorType=0&ErrorID=1115942
# &if $OSSPEC not in [WIN32]
# 
# # webagent fastcgi executable
# wafcgi.lnk			distrib
# 
# # build Apache 1.3 mod_fastcgi with session affinity patch
# # disabling make of apache and fastcgi, because with the higher
# # check level for warnings to many warnings will be traced in
# # external modules like mod_fastcgi.c, etc.
# # To distribute modfastcgi, we should use binaries
# # of the last version (MaO)
# fastcgi.mac
# 
# &endif
# 
# # WebAgent FastCGI distribution
# &if $OSSPEC not in [WIN32]
# 
# &if defined BIT64 && $OSSPEC not in [OSF1]
# 
# &if $OSSPEC in [HPUX]
# ? distribute : lib/lib64/mod_fastcgi.sl
# &else
# ? distribute : lib/lib64/mod_fastcgi.so
# &endif
# 
# &else
# 
# 
# &if $OSSPEC in [HPUX]
# ? distribute : lib/mod_fastcgi.sl
# &else
# ? distribute : lib/mod_fastcgi.so
# &endif
# 
# &endif
# 
# &endif

# Test-UserDlls
#wadbm.dld

# request simulator
#wasim.lnk			distrib

# DBFS WebAgent Service
#wafs.dld			distrib

# FTP-Service
#&if $OSSPEC in [WIN32]
#wainetd.lnk			distrib
#&endif
