*   *ID* A17SEL2  DBCMD    changed on 1992-09-28-13.22.45 by ADMIN     *
file connect ( kern test !
CREATE TABLE T2 ( A CHAR (4) KEY,
     B FIXED (5,2),
     C CHAR (21) NOT NULL,
     D CHAR (1) )!
INSERT T2 VALUES ('BAA', 34, 'WQERTT', 'C')!
INSERT T2 VALUES ('GAA', 34, 'WQERTT', 'C')!
INSERT T2 VALUES ('AAA', 34, 'WQERTT', 'C')!
INSERT T2 VALUES ('CAA', 34, 'WQERTT', 'C')!
DECLARE TE CURSOR FOR 
SELECT * FROM T2!
FETCH TE INTO :A, :B, :C, :D!
SELECT T2.* FROM T1!
FETCH !
SELECT T2.* FROM T2!
FETCH !
DECLARE TE CURSOR FOR 
SELECT * FROM T2!
FETCH TE!
close te !
DECLARE TE CURSOR FOR 
SELECT * FROM T2!
FETCH TE !
SELECT A, B, C, B, D FROM T2!
FETCH NEXT INTO :A, :B, :C, :D, :E !
SELECT DISTINCT    B, C, D FROM T2!
FETCH !
DECLARE ERG CURSOR FOR 
SELECT A, B FROM T2!
FETCH ERG !
SELECT A, B FROM T2 WHERE A > 'BAB' !
FETCH !
SELECT A, B INTO :A, :B FROM T2 !
SELECT A, B, C INTO :A, :B FROM T2 WHERE A < 'AZ'!
drop table t1 !
drop table t2 !
commit work release !
