*   *ID* BURRYDRO DBCMD    changed on 1992-09-28-13.22.52 by ADMIN     *
DROP DOMAIN DM_ADDRESSES !
DROP DOMAIN DM_BINS !
DROP DOMAIN DM_B_IDS !
DROP DOMAIN DM_CITIES !
DROP DOMAIN DM_CLASSIFICATIONS !
DROP DOMAIN DM_CREDITS !
DROP DOMAIN DM_C_IDS !
DROP DOMAIN DM_DATES !
commit work !
DROP DOMAIN DM_DESCRIPTIONS !
DROP DOMAIN DM_EMPLOYEE_IDS !
DROP DOMAIN DM_GRO_IDS !
DROP DOMAIN DM_IV_IDS !
DROP DOMAIN DM_M_IDS !
DROP DOMAIN DM_MONIES !
DROP DOMAIN DM_NAMES !
commit work !
DROP DOMAIN DM_PO_IDS !
DROP DOMAIN DM_PR_IDS !
DROP DOMAIN DM_QUANTITIES !
DROP DOMAIN DM_R_IDS !
DROP DOMAIN DM_REGION_IDS !
commit work !
DROP DOMAIN DM_ROUTES !
DROP DOMAIN DM_STATES !
DROP DOMAIN DM_SU_IDS !
DROP DOMAIN DM_ZIPCODES !
*
DROP TABLE kern.BRANCH !
DROP TABLE kern.CUSTOMER !
commit work !
DROP TABLE kern.GROUPTAB !
DROP TABLE kern.INVLINE !
commit work !
DROP TABLE kern.INVOICE !
DROP TABLE kern.MANIFEST !
commit work !
DROP TABLE kern.MANLINE !
DROP TABLE kern.PO !
commit work !
DROP TABLE kern.POLINE !
DROP TABLE kern.PRODUCT!
commit work !
DROP TABLE kern.RECEIVED !
DROP TABLE kern.REGION !
commit work !
DROP TABLE kern.STOCK !
DROP TABLE kern.STRUCTURE !
commit work !
DROP TABLE kern.SUPPLIER !
DROP TABLE kern.VS_NO !
commit work !
*
