select abs         ( &1                 ) into :a from &2 where k1 = 1 !
select acos        ( &1                 ) into :a from &2 where k1 = 1 !
select adddate     ( &1, 3              ) into :a from &2 where k1 = 1 !
select addtime     ( &1, '00013000'     ) into :a from &2 where k1 = 1 !
select alpha       ( &1                 ) into :a from &2 where k1 = 1 !
select ascii       ( &1                 ) into :a from &2 where k1 = 1 !
select asin        ( &1                 ) into :a from &2 where k1 = 1 !
select atan        ( &1                 ) into :a from &2 where k1 = 1 !
select atan2       ( &1, 8              ) into :a from &2 where k1 = 1 !
select case &1 when 'a' then 'b' else 'c' end into :a from &2 where k1 = 1 !
select ceil        ( &1                 ) into :a from &2 where k1 = 1 !
select ceiling     ( &1                 ) into :a from &2 where k1 = 1 !
select char        ( &1                 ) into :a from &2 where k1 = 1 !
select char        ( &1, internal       ) into :a from &2 where k1 = 1 !
select char        ( &1, iso            ) into :a from &2 where k1 = 1 !
select char        ( &1, usa            ) into :a from &2 where k1 = 1 !
select char        ( &1, jis            ) into :a from &2 where k1 = 1 !
select char        ( &1, eur            ) into :a from &2 where k1 = 1 !
select chr         ( &1                 ) into :a from &2 where k1 = 1 !
select               &1 || 'abc'          into :a from &2 where k1 = 1 !
select               'abc' || &1          into :a from &2 where k1 = 1 !
select concat      ( &1, 'abc'          ) into :a from &2 where k1 = 1 !
select cos         ( &1                 ) into :a from &2 where k1 = 1 !
select cosh        ( &1                 ) into :a from &2 where k1 = 1 !
select cot         ( &1                 ) into :a from &2 where k1 = 1 !
select datediff    ( &1, '19700731'     ) into :a from &2 where k1 = 1 !
select day         ( &1                 ) into :a from &2 where k1 = 1 !
select dayofmonth  ( &1                 ) into :a from &2 where k1 = 1 !
select dayofweek   ( &1                 ) into :a from &2 where k1 = 1 !
select dayofyear   ( &1                 ) into :a from &2 where k1 = 1 !
select decode      ( &1, &1, 5          ) into :a from &2 where k1 = 1 !
select degrees     ( &1                 ) into :a from &2 where k1 = 1 !
select digits      ( &1                 ) into :a from &2 where k1 = 1 !
select exp         ( &1                 ) into :a from &2 where k1 = 1 !
select expand      ( &1, 28             ) into :a from &2 where k1 = 1 !
select expand      ( &1, 320            ) into :a from &2 where k1 = 1 !
select expand      ( &1, 3200           ) into :a from &2 where k1 = 1 !
select fixed       ( &1, 18             ) into :a from &2 where k1 = 1 !
select float       ( &1, 7              ) into :a from &2 where k1 = 1 !
select floor       ( &1                 ) into :a from &2 where k1 = 1 !
select greatest    ( &1, &1             ) into :a from &2 where k1 = 1 !
select hex         ( &1                 ) into :a from &2 where k1 = 1 !
select hextoraw    ( &1                 ) into :a from &2 where k1 = 1 !
select hour        ( &1                 ) into :a from &2 where k1 = 1 !
select index       ( &1, '1'            ) into :a from &2 where k1 = 1 !
select index       ( &1, substr(' ',1,1)) into :a from &2 where k1 = 1 !
select initcap     ( &1                 ) into :a from &2 where k1 = 1 !
select least       ( &1, &1             ) into :a from &2 where k1 = 1 !
select length      ( &1                 ) into :a from &2 where k1 = 1 !
select lfill       ( &1, 'q'            ) into :a from &2 where k1 = 1 !
select ln          ( &1                 ) into :a from &2 where k1 = 1 !
select locate      ( 'a', &1            ) into :a from &2 where k1 = 1 !
select locate      ( &1, 'a'            ) into :a from &2 where k1 = 1 !
select lower       ( &1                 ) into :a from &2 where k1 = 1 !
select log         ( 10, &1             ) into :a from &2 where k1 = 1 !
select log10       ( &1                 ) into :a from &2 where k1 = 1 !
select lpad        ( &1, 3, 'q'         ) into :a from &2 where k1 = 1 !
select ltrim       ( &1                 ) into :a from &2 where k1 = 1 !
select ltrim       ( &1, 'ae0123'       ) into :a from &2 where k1 = 1 !
select makedate    ( &1, 31             ) into :a from &2 where k1 = 1 !
select maketime    ( &1, 40, 13         ) into :a from &2 where k1 = 1 !
select mapchar     ( &1                 ) into :a from &2 where k1 = 1 !
select minute      ( &1                 ) into :a from &2 where k1 = 1 !
select month       ( &1                 ) into :a from &2 where k1 = 1 !
select monthname   ( &1                 ) into :a from &2 where k1 = 1 !
select num         ( &1                 ) into :a from &2 where k1 = 1 !
select power       ( &1, 3              ) into :a from &2 where k1 = 1 !
select replace     ( &1, 'c', 's'       ) into :a from &2 where k1 = 1 !
select rfill       ( &1, 'q'            ) into :a from &2 where k1 = 1 !
select round       ( &1                 ) into :a from &2 where k1 = 1 !
select rpad        ( &1, 3, 'q'         ) into :a from &2 where k1 = 1 !
select rtrim       ( &1                 ) into :a from &2 where k1 = 1 !
select rtrim       ( &1, 'ae0123'       ) into :a from &2 where k1 = 1 !
select second      ( &1                 ) into :a from &2 where k1 = 1 !
select sign        ( &1                 ) into :a from &2 where k1 = 1 !
select sin         ( &1                 ) into :a from &2 where k1 = 1 !
select sinh        ( &1                 ) into :a from &2 where k1 = 1 !
select soundex     ( &1                 ) into :a from &2 where k1 = 1 !
select space       ( &1                 ) into :a from &2 where k1 = 1 !
select sqrt        ( &1                 ) into :a from &2 where k1 = 1 !
select subdate     ( &1, 1              ) into :a from &2 where k1 = 1 !
select substr      ( &1, 4, 3           ) into :a from &2 where k1 = 1 !
select substr      ( &1, 260, 3         ) into :a from &2 where k1 = 1 !
select substr      ( &1, 2600, 3        ) into :a from &2 where k1 = 1 !
select substring   ( &1, 4, 3           ) into :a from &2 where k1 = 1 !
select subtime     ( &1, '00013000'     ) into :a from &2 where k1 = 1 !
select tan         ( &1                 ) into :a from &2 where k1 = 1 !
select tanh        ( &1                 ) into :a from &2 where k1 = 1 !
select time        ( &1                 ) into :a from &2 where k1 = 1 !
select timediff    ( &1, '00013000'     ) into :a from &2 where k1 = 1 !
select translate   ( &1, 'c', 's'       ) into :a from &2 where k1 = 1 !
select trim        ( &1                 ) into :a from &2 where k1 = 1 !
select trim        ( &1, 'ae0123'       ) into :a from &2 where k1 = 1 !
select trunc       ( &1                 ) into :a from &2 where k1 = 1 !
select upper       ( &1                 ) into :a from &2 where k1 = 1 !
select value       ( &1, 2              ) into :a from &2 where k1 = 1 !
select weekofyear  ( &1                 ) into :a from &2 where k1 = 1 !
select year        ( &1                 ) into :a from &2 where k1 = 1 !
