&2
SELECT &1 FROM u
  WHERE u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 = 111
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 >= 111
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 < 222
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 >= 111
    AND u1 BETWEEN 11 AND 12
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 < 222
    AND u1 BETWEEN 11 AND 12
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE (u4 < 222 AND u1 BETWEEN 11 AND 12)
    OR  u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!

&2
SELECT &1 FROM u
  WHERE u4 IN (NULL, 222, 111,  555)
    AND u5 IN (NULL, 'DDD', 'CCC', 'BBB', NULL, 'AAA', NULL)!
&3 FETCH!
