*   *ID* LOCK24   DBCMD    changed on 1992-09-28-13.24.35 by ADMIN     *
CONNECT KERN TEST!
CREATE TABLE T ( A CHAR (8) ASCII KEY)!
INSERT T SET A = 'aaa'!
INSERT T SET A = 'bbb'!
COMMIT !
SELECT ERG(*) FROM T FOR REUSE !
SELECT * FROM SYSDD.LOCKS WHERE TABLENAME <> 'DUAL' !
fetch !
COMMIT !
SELECT ERG(*) FROM T WITH LOCK FOR REUSE !
SELECT * FROM SYSDD.LOCKS WHERE TABLENAME <> 'DUAL' !
fetch !
COMMIT !
SELECT ERG(*) FROM T WITH LOCK SHARE FOR REUSE !
SELECT * FROM SYSDD.LOCKS WHERE TABLENAME <> 'DUAL' !
fetch !
COMMIT !
SELECT ERG(*) FROM T WITH LOCK (WAIT) EXCLUSIVE FOR REUSE !
SELECT * FROM SYSDD.LOCKS WHERE TABLENAME <> 'DUAL' !
fetch !
COMMIT !
SELECT ERG(*) FROM T WITH LOCK (WAIT) EXCLUSIVE
    ISOLATION LEVEL 15 FOR REUSE !
commit release !
