*   *ID* N36GROU3 DBCMD    changed on 1992-09-28-13.26.24 by ADMIN     *
file connect ( kern test !
CREATE TABLE kern.SYSMSG
             ( COMPONENT  CHAR  (12)    ASCII KEY,
               LANGUAGE   CHAR  (03)    ASCII KEY,
               MSGNO      FIXED (5,0)         KEY,
               MSGTEXT    CHAR  (160)   ASCII )   !
GRANT SELECT ON kern.SYSMSG TO PUBLIC !
commit work !
insert kern.sysmsg values ('DBKERN', 'GER', - 1, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 2, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 3, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 4, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 5, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 6, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 7, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 8, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', - 9, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  10, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  11, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  12, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  13, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  14, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  15, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  17, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  18, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  19, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  20, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  21, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  22, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  23, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  24, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  25, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  26, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  27, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  28, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  29, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  30, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  31, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  32, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  33, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  34, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  35, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  36, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  37, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  38, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  39, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  40, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  41, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  42, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  43, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  44, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  45, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  46, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  47, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  48, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  49, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  50, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  51, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  52, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  53, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  54, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  55, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  56, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  57, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  58, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  59, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  60, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  61, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  62, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  63, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  64, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  65, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  66, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  67, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  68, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  69, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  70, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  71, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  72, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  73, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  74, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  75, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  76, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  77, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  78, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  79, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  80, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  81, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  82, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  83, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  84, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  85, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  86, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  87, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  88, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  89, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  90, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  91, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  92, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  93, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  94, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  95, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  96, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  97, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  98, 'xxx' ) !
insert kern.sysmsg values ('DBKERN', 'GER', -  99, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 1, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 2, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 3, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 4, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 5, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 6, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 7, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 8, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', - 9, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  10, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  11, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  12, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  13, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  14, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  15, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  17, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  18, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  19, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  20, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  21, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  22, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  23, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  24, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  25, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  26, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  27, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  28, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  29, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  30, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  31, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  32, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  33, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  34, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  35, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  36, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  37, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  38, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  39, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  40, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  41, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  42, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  43, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  44, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  45, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  46, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  47, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  48, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  49, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  50, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  51, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  52, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  53, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  54, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  55, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  56, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  57, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  58, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  59, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  60, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  61, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  62, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  63, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  64, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  65, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  66, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  67, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  68, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  69, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  70, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  71, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  72, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  73, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  74, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  75, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  76, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  77, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  78, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  79, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  80, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  81, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  82, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  83, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  84, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  85, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  86, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  87, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  88, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  89, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  90, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  91, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  92, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  93, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  94, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  95, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  96, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  97, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  98, 'xxx' ) !
insert kern.sysmsg values ('QUERY', 'GER', -  99, 'xxx' ) !
commit work !
select component, count(msgno) from kern.sysmsg
   where component = 'GER' group by component !
fetch !
commit work release !
