
*   *ID* ORADDROP CMD      changed on 1994-05-18-11.38.43 by KRISCHAN  *

file CONNECT ( sys sys SQLMODE oracle!

* Most of the user_* views are defined in terms of other dd-views, so
* let's drop them first!
DROP VIEW user_audit_connect!
DROP VIEW user_audit_object!
DROP VIEW user_audit_resource!
DROP VIEW user_audit_session!
DROP VIEW user_audit_statements!
DROP VIEW user_audit_trail!
DROP VIEW user_catalog!
DROP VIEW user_clu_columns!
DROP VIEW user_clusters!
DROP VIEW user_col_comments!
DROP VIEW user_col_grants!
DROP VIEW user_col_grants_made!
DROP VIEW user_col_grants_recd!
DROP VIEW user_col_privs!
DROP VIEW user_col_privs_made!
DROP VIEW user_col_privs_recd!
DROP VIEW user_cons_columns!
DROP VIEW user_constraints!
DROP VIEW user_cross_refs!
DROP VIEW user_db_links!
DROP VIEW user_extents!
DROP VIEW user_free_space!
DROP VIEW user_ind_columns!
DROP VIEW user_indexes!
DROP VIEW user_obj_audit_opts!
DROP VIEW user_object_size!
DROP VIEW user_objects!
DROP VIEW user_resource_limit!
DROP VIEW user_role_privs!
DROP VIEW user_segments!
DROP VIEW user_sequences!
DROP VIEW user_snapshot_logs!
DROP VIEW user_snapshots!
DROP VIEW user_synonyms!
DROP VIEW user_sys_privs!
DROP VIEW user_tab_audit_opts!
DROP VIEW user_tab_columns!
DROP VIEW user_tab_grants!
DROP VIEW user_tab_grants_made!
DROP VIEW user_tab_grants_recd!
DROP VIEW user_tab_privs!
DROP VIEW user_tab_privs_made!
DROP VIEW user_tab_privs_recd!
DROP VIEW user_tables!
DROP VIEW user_tablespaces!
DROP VIEW user_trigger_cols!
DROP VIEW user_triggers!
DROP VIEW user_ts_quotas!
DROP VIEW user_users!
DROP VIEW user_views!
COMMIT WORK!

DROP VIEW accessible_columns!
DROP VIEW accessible_tables!
DROP VIEW all_catalog!
DROP VIEW all_col_comments!
DROP VIEW all_col_grants_made!
DROP VIEW all_col_grants_recd!
DROP VIEW all_col_privs!
DROP VIEW all_col_privs_made!
DROP VIEW all_col_privs_recd!
DROP VIEW all_cons_columns!
DROP VIEW all_constraints!
DROP VIEW all_db_links!
DROP VIEW all_def_audit_opts!
DROP VIEW all_dependencies!
DROP VIEW all_errors!
DROP VIEW all_ind_columns!
DROP VIEW all_indexes!
DROP VIEW all_objects!
DROP VIEW all_sequences!
DROP VIEW all_snapshots!
DROP VIEW all_source!
DROP VIEW all_synonyms!
DROP VIEW all_tab_columns!
DROP VIEW all_tab_comments!
DROP VIEW all_tab_grants_made!
DROP VIEW all_tab_grants_recd!
DROP VIEW all_tab_privs!
DROP VIEW all_tab_privs_made!
DROP VIEW all_tab_privs_recd!
DROP VIEW all_tables!
DROP VIEW all_trigger_cols!
DROP VIEW all_triggers!
DROP VIEW all_users!
DROP VIEW all_views!
COMMIT WORK!

DROP VIEW column_privileges!
DROP VIEW constraint_columns!
DROP VIEW constraint_defs!
DROP VIEW dba_2pc_neighbors!
DROP VIEW dba_2pc_pending!
DROP VIEW dba_audit_object!
DROP VIEW dba_audit_session!
DROP VIEW dba_audit_statemen!
DROP VIEW dba_audit_trail!
DROP VIEW dba_blockers!
DROP VIEW dba_catalog!
DROP VIEW dba_clu_columns!
DROP VIEW dba_clusters!
DROP VIEW dba_col_comments!
DROP VIEW dba_col_grants!
DROP VIEW dba_col_privs!
DROP VIEW dba_cons_columns!
DROP VIEW dba_constraints!
DROP VIEW dba_cross_refs!
DROP VIEW dba_data_files!
DROP VIEW dba_db_links!
DROP VIEW dba_ddl_locks!
DROP VIEW dba_dependencies!
DROP VIEW dba_dml_locks!
DROP VIEW dba_errors!
DROP VIEW dba_exp_files!
DROP VIEW dba_exp_objects!
DROP VIEW dba_exp_version!
DROP VIEW dba_extents!
DROP VIEW dba_free_space!
DROP VIEW dba_ind_columns!
DROP VIEW dba_indexes!
DROP VIEW dba_locks!
DROP VIEW dba_obj_audit_opts!
DROP VIEW dba_object_size!
DROP VIEW dba_objects!
DROP VIEW dba_priv_audit_opt!
DROP VIEW dba_profiles!
DROP VIEW dba_role_privs!
DROP VIEW dba_roles!
DROP VIEW dba_rollback_segs!
DROP VIEW dba_segments!
DROP VIEW dba_sequences!
DROP VIEW dba_snapshot_logs!
DROP VIEW dba_snapshots!
DROP VIEW dba_source!
DROP VIEW dba_stmt_audit_opt!
DROP VIEW dba_synonyms!
DROP VIEW dba_sys_audit_opts!
DROP VIEW dba_sys_privs!
DROP VIEW dba_tab_audit_opts!
DROP VIEW dba_tab_columns!
DROP VIEW dba_tab_comments!
DROP VIEW dba_tab_grants!
DROP VIEW dba_tab_privs!
DROP VIEW dba_tables!
DROP VIEW dba_tablespaces!
DROP VIEW dba_trigger_cols!
DROP VIEW dba_triggers!
DROP VIEW dba_ts_quotas!
DROP VIEW dba_users!
DROP VIEW dba_views!
DROP VIEW dba_waiters!
DROP VIEW dict_columns!
DROP VIEW dictionary!
DROP VIEW exceptions!
DROP VIEW global_name!
DROP VIEW public_dependency!
DROP VIEW resource_cost!
DROP VIEW role_role_privs!
DROP VIEW role_sys_privs!
DROP VIEW role_tab_privs!
DROP VIEW session_privs!
DROP VIEW session_roles!
DROP VIEW table_privileges!
COMMIT WORK!

DROP TABLE audit_actions!
DROP TABLE stmt_audit_option_map!
DROP TABLE table_privilege_map!
COMMIT WORK RELEASE!
