*** STAUAS.cmd ***
* Aufruf in STAUAA.cmd und STAUAB.cmd
*
* Selektieren auf den VIEWs
SELECT * FROM VE&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VW&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VS&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VX&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VY&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VZ&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VA&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VB&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VC&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VD&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VF&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VG&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VH&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VI&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VJ&1!
IF $RC = 0 THEN FETCH!
*
SELECT * FROM VK&1!
IF $RC = 0 THEN FETCH!
*
