/*
        ========== licence begin  GPL
        Copyright (c) 2005 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end

*/

#ifndef SDBMSG_DBMSCD_H
#define SDBMSG_DBMSCD_H
/*
This header file was generated by buildmsg.pl
--- Do not edit....
*/
#ifdef __cplusplus
#ifndef MSG_LIST_HPP
#include "SAPDB/Messages/Msg_List.hpp"
#endif
#ifndef MSG_ARG_HPP
#include "SAPDB/Messages/Msg_Arg.hpp"
#endif
#ifndef MSG_SIMPLEARG_HPP
#include "SAPDB/Messages/Msg_SimpleArg.hpp"
#endif
#endif

#ifndef SDB_RELEASE_070600  /* don't merge this define - only this date: 2005-04-12 18:13:37 */
#error SDBMsg_DBMScd.h was probably integrated between releases, do not integrate this header file, \
use buildmsg
#endif


#define SDBMSG_DBMSCD_COMPONENT "DBMScd"
/* Begin of all message defines for component DBMScd -> */
/* Begin of defines for message ACTION_TERMINATION: ID = 1, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_TERMINATION 1, "DBMScd", __FILE__, __LINE__, "terminate", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_TERMINATION */
/* Begin of defines for message ACTION_INSERTJOB: ID = 2, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_INSERTJOB 2, "DBMScd", __FILE__, __LINE__, "insert new scheduler job", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_INSERTJOB */
/* Begin of defines for message ACTION_RETURNJOBLIST: ID = 3, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_RETURNJOBLIST 3, "DBMScd", __FILE__, __LINE__, "list of scheduler jobs requested", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_RETURNJOBLIST */
/* Begin of defines for message ACTION_ACTIVATEJOB: ID = 4, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_ACTIVATEJOB 4, "DBMScd", __FILE__, __LINE__, "activate scheduler job", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_ACTIVATEJOB */
/* Begin of defines for message ACTION_DEACTIVATEJOB: ID = 5, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_DEACTIVATEJOB 5, "DBMScd", __FILE__, __LINE__, "deactivate scheduler job", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_DEACTIVATEJOB */
/* Begin of defines for message ACTION_DELETEJOB: ID = 6, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_DELETEJOB 6, "DBMScd", __FILE__, __LINE__, "delete scheduler job", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_DELETEJOB */
/* Begin of defines for message JOBSERVEDBYPID: ID = 7, VERSION = 1, TAGS = 4 -> */
#define SDBMSG_DBMSCD_JOBSERVEDBYPID 7, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: served by PID $PID$ ($PIDASHEX$)", (Msg_Has4Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBSERVEDBYPID__PID "PID"
#define SDBMSGTAG_DBMSCD_JOBSERVEDBYPID__PIDASHEX "PIDASHEX"
#define SDBMSGTAG_DBMSCD_JOBSERVEDBYPID__SCDJOBID "SCDJOBID"
/* <- End of defines for message JOBSERVEDBYPID */
/* Begin of defines for message JOBEXECUTEDAT: ID = 8, VERSION = 1, TAGS = 5 -> */
#define SDBMSG_DBMSCD_JOBEXECUTEDAT 8, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: planned execution time $DATE$, $TIME$ (dbm_command: $DBMCMD$)", (Msg_Has5Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAT__DATE "DATE"
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAT__DBMCMD "DBMCMD"
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAT__SCDJOBID "SCDJOBID"
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAT__TIME "TIME"
/* <- End of defines for message JOBEXECUTEDAT */
/* Begin of defines for message JOBEXECUTEDAFTER: ID = 9, VERSION = 1, TAGS = 4 -> */
#define SDBMSG_DBMSCD_JOBEXECUTEDAFTER 9, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: planned execution after scheduler job $SCDJOBIDPRED$ (dbm_command: $DBMCMD$)", (Msg_Has4Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAFTER__DBMCMD "DBMCMD"
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAFTER__SCDJOBID "SCDJOBID"
#define SDBMSGTAG_DBMSCD_JOBEXECUTEDAFTER__SCDJOBIDPRED "SCDJOBIDPRED"
/* <- End of defines for message JOBEXECUTEDAFTER */
/* Begin of defines for message ERRLOGPLANNEDEXECUTION: ID = 10, VERSION = 1, TAGS = 2 -> */
#define SDBMSG_DBMSCD_ERRLOGPLANNEDEXECUTION 10, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: cannot log planned execution time", (Msg_Has2Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_ERRLOGPLANNEDEXECUTION__SCDJOBID "SCDJOBID"
/* <- End of defines for message ERRLOGPLANNEDEXECUTION */
/* Begin of defines for message JOBREPLY: ID = 11, VERSION = 1, TAGS = 3 -> */
#define SDBMSG_DBMSCD_JOBREPLY 11, "DBMScd", __FILE__, __LINE__, "reply of scheduler job $SCDJOBID$", (Msg_Has3Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBREPLY__SCDJOBID "SCDJOBID"
#define SDBMSGTAG_DBMSCD_JOBREPLY__SCDJOBREPLY "SCDJOBREPLY"
/* <- End of defines for message JOBREPLY */
/* Begin of defines for message ERRNOJOBREPLY: ID = 12, VERSION = 1, TAGS = 2 -> */
#define SDBMSG_DBMSCD_ERRNOJOBREPLY 12, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: no reply available", (Msg_Has2Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_ERRNOJOBREPLY__SCDJOBID "SCDJOBID"
/* <- End of defines for message ERRNOJOBREPLY */
/* Begin of defines for message JOBFINISHEDAFTER: ID = 13, VERSION = 1, TAGS = 3 -> */
#define SDBMSG_DBMSCD_JOBFINISHEDAFTER 13, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: finished (planned execution after scheduler job $SCDJOBIDPRED$).", (Msg_Has3Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBFINISHEDAFTER__SCDJOBID "SCDJOBID"
#define SDBMSGTAG_DBMSCD_JOBFINISHEDAFTER__SCDJOBIDPRED "SCDJOBIDPRED"
/* <- End of defines for message JOBFINISHEDAFTER */
/* Begin of defines for message JOBFINISHEDAT: ID = 14, VERSION = 1, TAGS = 4 -> */
#define SDBMSG_DBMSCD_JOBFINISHEDAT 14, "DBMScd", __FILE__, __LINE__, "scheduler job $SCDJOBID$: finished (planned execution time $DATE$, $TIME$)", (Msg_Has4Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_DBMSCD_JOBFINISHEDAT__DATE "DATE"
#define SDBMSGTAG_DBMSCD_JOBFINISHEDAT__SCDJOBID "SCDJOBID"
#define SDBMSGTAG_DBMSCD_JOBFINISHEDAT__TIME "TIME"
/* <- End of defines for message JOBFINISHEDAT */
/* Begin of defines for message ACTION_START: ID = 15, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ACTION_START 15, "DBMScd", __FILE__, __LINE__, "start", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ACTION_START */
/* Begin of defines for message ERRUNKNOWNCOMMAND: ID = 16, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_ERRUNKNOWNCOMMAND 16, "DBMScd", __FILE__, __LINE__, "unknown scheduler command", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message ERRUNKNOWNCOMMAND */
/* Begin of defines for message NO_PID_ENTERED: ID = 17, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_NO_PID_ENTERED 17, "DBMScd", __FILE__, __LINE__, "Could not enter PID into Shared Memory", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message NO_PID_ENTERED */
/* Begin of defines for message NO_START: ID = 18, VERSION = 1, TAGS = 1 -> */
#define SDBMSG_DBMSCD_NO_START 18, "DBMScd", __FILE__, __LINE__, "DBM Command Scheduler cannot start", (Msg_Has1Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
/* <- End of defines for message NO_START */
/* <- End of message defines for component DBMScd */

/* some helpful enumerations (created by buildmsg.pl) -> */

#define SDBMSG_DBMSCD_ENUMERATION \
                    DBMScd_ACTION_TERMINATION=1, \
                    DBMScd_ACTION_INSERTJOB=2, \
                    DBMScd_ACTION_RETURNJOBLIST=3, \
                    DBMScd_ACTION_ACTIVATEJOB=4, \
                    DBMScd_ACTION_DEACTIVATEJOB=5, \
                    DBMScd_ACTION_DELETEJOB=6, \
                    DBMScd_JOBSERVEDBYPID=7, \
                    DBMScd_JOBEXECUTEDAT=8, \
                    DBMScd_JOBEXECUTEDAFTER=9, \
                    DBMScd_ERRLOGPLANNEDEXECUTION=10, \
                    DBMScd_JOBREPLY=11, \
                    DBMScd_ERRNOJOBREPLY=12, \
                    DBMScd_JOBFINISHEDAFTER=13, \
                    DBMScd_JOBFINISHEDAT=14, \
                    DBMScd_ACTION_START=15, \
                    DBMScd_ERRUNKNOWNCOMMAND=16, \
                    DBMScd_NO_PID_ENTERED=17, \
                    DBMScd_NO_START=18
#define SDBMSG_DBMSCD_INITIALIZATIONLIST(x) \
                    x(SDBMSG_DBMSCD_ACTION_TERMINATION, "ACTION_TERMINATION"), \
                    x(SDBMSG_DBMSCD_ACTION_INSERTJOB, "ACTION_INSERTJOB"), \
                    x(SDBMSG_DBMSCD_ACTION_RETURNJOBLIST, "ACTION_RETURNJOBLIST"), \
                    x(SDBMSG_DBMSCD_ACTION_ACTIVATEJOB, "ACTION_ACTIVATEJOB"), \
                    x(SDBMSG_DBMSCD_ACTION_DEACTIVATEJOB, "ACTION_DEACTIVATEJOB"), \
                    x(SDBMSG_DBMSCD_ACTION_DELETEJOB, "ACTION_DELETEJOB"), \
                    x(SDBMSG_DBMSCD_JOBSERVEDBYPID, "JOBSERVEDBYPID"), \
                    x(SDBMSG_DBMSCD_JOBEXECUTEDAT, "JOBEXECUTEDAT"), \
                    x(SDBMSG_DBMSCD_JOBEXECUTEDAFTER, "JOBEXECUTEDAFTER"), \
                    x(SDBMSG_DBMSCD_ERRLOGPLANNEDEXECUTION, "ERRLOGPLANNEDEXECUTION"), \
                    x(SDBMSG_DBMSCD_JOBREPLY, "JOBREPLY"), \
                    x(SDBMSG_DBMSCD_ERRNOJOBREPLY, "ERRNOJOBREPLY"), \
                    x(SDBMSG_DBMSCD_JOBFINISHEDAFTER, "JOBFINISHEDAFTER"), \
                    x(SDBMSG_DBMSCD_JOBFINISHEDAT, "JOBFINISHEDAT"), \
                    x(SDBMSG_DBMSCD_ACTION_START, "ACTION_START"), \
                    x(SDBMSG_DBMSCD_ERRUNKNOWNCOMMAND, "ERRUNKNOWNCOMMAND"), \
                    x(SDBMSG_DBMSCD_NO_PID_ENTERED, "NO_PID_ENTERED"), \
                    x(SDBMSG_DBMSCD_NO_START, "NO_START")
/* <- some helpful enumerations */

#endif /* SDBMSG_DBMSCD_H */
