/*
        ========== licence begin  GPL
        Copyright (c) 2005 SAP AG

        This program is free software; you can redistribute it and/or
        modify it under the terms of the GNU General Public License
        as published by the Free Software Foundation; either version 2
        of the License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with this program; if not, write to the Free Software
        Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
        ========== licence end

*/

#ifndef SDBMSG_INDEX_H
#define SDBMSG_INDEX_H
/*
This header file was generated by buildmsg.pl
--- Do not edit....
*/
#ifdef __cplusplus
#ifndef MSG_LIST_HPP
#include "SAPDB/Messages/Msg_List.hpp"
#endif
#ifndef MSG_ARG_HPP
#include "SAPDB/Messages/Msg_Arg.hpp"
#endif
#ifndef MSG_SIMPLEARG_HPP
#include "SAPDB/Messages/Msg_SimpleArg.hpp"
#endif
#endif

#ifndef SDB_RELEASE_070600  /* don't merge this define - only this date: 2005-11-14 14:17:19 */
#error SDBMsg_Index.h was probably integrated between releases, do not integrate this header file, \
use buildmsg
#endif


#define SDBMSG_INDEX_COMPONENT "Index"
/* Begin of all message defines for component Index -> */
/* Begin of defines for message RECINDEX_OUT_OF_RANGE: ID = 1, VERSION = 1, TAGS = 3 -> */
#define SDBMSG_INDEX_RECINDEX_OUT_OF_RANGE 1, "Index", __FILE__, __LINE__, "RecIndex $RECINDEX$ is wanted, but $MAXRECINDEX$ is the greatest.", (Msg_Has3Args*)0, Msg_SimpleArg("_MESSAGEVERSION", reinterpret_cast<const SAPDB_UTF8*>("1"))
#define SDBMSGTAG_INDEX_RECINDEX_OUT_OF_RANGE__RECINDEX "RECINDEX"
#define SDBMSGTAG_INDEX_RECINDEX_OUT_OF_RANGE__MAXRECINDEX "MAXRECINDEX"
/* <- End of defines for message RECINDEX_OUT_OF_RANGE */
/* <- End of message defines for component Index */

/* some helpful enumerations (created by buildmsg.pl) -> */

#define SDBMSG_INDEX_ENUMERATION \
                    Index_RECINDEX_OUT_OF_RANGE=1
#define SDBMSG_INDEX_INITIALIZATIONLIST(x) \
                    x(SDBMSG_INDEX_RECINDEX_OUT_OF_RANGE, "RECINDEX_OUT_OF_RANGE")
/* <- some helpful enumerations */

#endif /* SDBMSG_INDEX_H */
