#  @(#)dbmcp.mac     7.2.0   1998-12-15
#  core Perl dbm wrapper
#
#
#
#    ========== licence begin  GPL
#    Copyright (c) 2000-2005 SAP AG
#
#    This program is free software; you can redistribute it and/or
#    modify it under the terms of the GNU General Public License
#    as published by the Free Software Foundation; either version 2
#    of the License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#    ========== licence end

&if $COREPERL_INCLUDE <> NO
# build only if Perl includes can be found

&if ( not defined BIT64 ) or ( $OSSPEC in [ OSF1 ] )
# build only 32 bit versions

::SAPDB/Scripting/Resource/dbmcperl.dld distrib
:SAPDB/Scripting/dbm.pm distrib

&if ! defined XCOMP
# test module can be loaded
#&if $OS = WIN32
#! SET PERL5LIB=%INSTMISC%& perl -e "use SAP::DBTech::dbm;"
#&else
#! PERL5LIB=$INSTMISC perl -e "use SAP::DBTech::dbm;"
#&endif
&endif

&endif
&endif

